// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Pin fields match red authoring circle id attributes in catalog SVGs (see vectors_gen.go RegisterPinLayout).

package relay

import "coilforge/internal/core"

// RelayPinIDs holds stable pin identity for this catalog type.
type RelayPinIDs struct {
	COM core.PinID `json:"cOM"`
	CoilA core.PinID `json:"coilA"`
	CoilB core.PinID `json:"coilB"`
	NC core.PinID `json:"nC"`
	NO core.PinID `json:"nO"`
}

// relayPinMarkerMap maps SVG marker ids from the vector layout to pin IDs for anchor placement.
func relayPinMarkerMap(self *Relay) map[string]core.PinID {
	return map[string]core.PinID{
		"COM": self.COM,
		"CoilA": self.CoilA,
		"CoilB": self.CoilB,
		"NC": self.NC,
		"NO": self.NO,
	}
}

// assignNewRelayPins allocates fresh pin IDs (e.g. clone).
func assignNewRelayPins(self *Relay, alloc func() core.PinID) {
	self.COM = alloc()
	self.CoilA = alloc()
	self.CoilB = alloc()
	self.NC = alloc()
	self.NO = alloc()
}
