// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Vector names are <stem>-<0..n> from schematic SVGs (underscores → hyphens), excluding toolbar btn_*.svg.
// Without _45: indices 0..3 are quarter-turn steps of the canonical SVG.
// With *-stem_45.svg: indices 0..7 interleave canonical and diagonal art (even idx = canonical, odd = _45); idx/2 is the quarter-turn on that source.
// Each suffix bakes k BasePart.Rotation steps in SVG user space (same convention as core.LocalToWorld); catalog draw passes identity rotation.
package relay

import (
	"coilforge/internal/core"
	"coilforge/internal/part"
	"image/color"
)

const RotationSlots = 4

func init() {
	part.RegisterVectorDraw("coil-off-0", drawVector_coil_off_0)
	part.RegisterPinLayout("coil-off-0", []core.Pt{
		{X:-96.000000, Y:0.000000},
		{X:96.000000, Y:0.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-off-0", -128.000000, -129.000000, 128.000000, 2.000000)
	part.RegisterVectorDraw("coil-off-1", drawVector_coil_off_1)
	part.RegisterPinLayout("coil-off-1", []core.Pt{
		{X:-0.000000, Y:-96.000000},
		{X:-0.000000, Y:96.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-off-1", -2.000000, -128.000000, 129.000000, 128.000000)
	part.RegisterVectorDraw("coil-off-2", drawVector_coil_off_2)
	part.RegisterPinLayout("coil-off-2", []core.Pt{
		{X:96.000000, Y:-0.000000},
		{X:-96.000000, Y:-0.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-off-2", -128.000000, -2.000000, 128.000000, 129.000000)
	part.RegisterVectorDraw("coil-off-3", drawVector_coil_off_3)
	part.RegisterPinLayout("coil-off-3", []core.Pt{
		{X:0.000000, Y:96.000000},
		{X:0.000000, Y:-96.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-off-3", -129.000000, -128.000000, 2.000000, 128.000000)
	part.RegisterVectorDraw("coil-on-0", drawVector_coil_on_0)
	part.RegisterPinLayout("coil-on-0", []core.Pt{
		{X:-96.000000, Y:0.000000},
		{X:96.000000, Y:0.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-on-0", -128.000000, -129.000000, 128.000000, 2.000000)
	part.RegisterVectorDraw("coil-on-1", drawVector_coil_on_1)
	part.RegisterPinLayout("coil-on-1", []core.Pt{
		{X:-0.000000, Y:-96.000000},
		{X:-0.000000, Y:96.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-on-1", -2.000000, -128.000000, 129.000000, 128.000000)
	part.RegisterVectorDraw("coil-on-2", drawVector_coil_on_2)
	part.RegisterPinLayout("coil-on-2", []core.Pt{
		{X:96.000000, Y:-0.000000},
		{X:-96.000000, Y:-0.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-on-2", -128.000000, -2.000000, 128.000000, 129.000000)
	part.RegisterVectorDraw("coil-on-3", drawVector_coil_on_3)
	part.RegisterPinLayout("coil-on-3", []core.Pt{
		{X:0.000000, Y:96.000000},
		{X:0.000000, Y:-96.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-on-3", -129.000000, -128.000000, 2.000000, 128.000000)
	part.RegisterVectorDraw("mid-flight-0", drawVector_mid_flight_0)
	part.RegisterPinLayout("mid-flight-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:-64.000000},
		{X:128.000000, Y:64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-flight-0", -128.000000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-flight-1", drawVector_mid_flight_1)
	part.RegisterPinLayout("mid-flight-1", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:64.000000, Y:128.000000},
		{X:-64.000000, Y:128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-flight-1", -96.000000, -128.000000, 96.000000, 128.000000)
	part.RegisterVectorDraw("mid-flight-2", drawVector_mid_flight_2)
	part.RegisterPinLayout("mid-flight-2", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:64.000000},
		{X:-128.000000, Y:-64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-flight-2", -128.000000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-flight-3", drawVector_mid_flight_3)
	part.RegisterPinLayout("mid-flight-3", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:-64.000000, Y:-128.000000},
		{X:64.000000, Y:-128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-flight-3", -96.000000, -128.000000, 96.000000, 128.000000)
	part.RegisterVectorDraw("mid-off-0", drawVector_mid_off_0)
	part.RegisterPinLayout("mid-off-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:-64.000000},
		{X:128.000000, Y:64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-off-0", -128.000000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-off-1", drawVector_mid_off_1)
	part.RegisterPinLayout("mid-off-1", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:64.000000, Y:128.000000},
		{X:-64.000000, Y:128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-off-1", -96.000000, -128.000000, 96.000000, 128.000000)
	part.RegisterVectorDraw("mid-off-2", drawVector_mid_off_2)
	part.RegisterPinLayout("mid-off-2", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:64.000000},
		{X:-128.000000, Y:-64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-off-2", -128.000000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-off-3", drawVector_mid_off_3)
	part.RegisterPinLayout("mid-off-3", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:-64.000000, Y:-128.000000},
		{X:64.000000, Y:-128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-off-3", -96.000000, -128.000000, 96.000000, 128.000000)
	part.RegisterVectorDraw("mid-on-0", drawVector_mid_on_0)
	part.RegisterPinLayout("mid-on-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:-64.000000},
		{X:128.000000, Y:64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-on-0", -128.000000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-on-1", drawVector_mid_on_1)
	part.RegisterPinLayout("mid-on-1", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:64.000000, Y:128.000000},
		{X:-64.000000, Y:128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-on-1", -96.000000, -128.000000, 96.000000, 128.000000)
	part.RegisterVectorDraw("mid-on-2", drawVector_mid_on_2)
	part.RegisterPinLayout("mid-on-2", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:64.000000},
		{X:-128.000000, Y:-64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-on-2", -128.000000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-on-3", drawVector_mid_on_3)
	part.RegisterPinLayout("mid-on-3", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:-64.000000, Y:-128.000000},
		{X:64.000000, Y:-128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-on-3", -96.000000, -128.000000, 96.000000, 128.000000)
	part.RegisterVectorDraw("top-0", drawVector_top_0)
	part.RegisterVectorHitBounds("top-0", -128.000000, -32.000000, 128.000000, 0.000000)
	part.RegisterVectorDraw("top-1", drawVector_top_1)
	part.RegisterVectorHitBounds("top-1", -0.000000, -128.000000, 32.000000, 128.000000)
	part.RegisterVectorDraw("top-2", drawVector_top_2)
	part.RegisterVectorHitBounds("top-2", -128.000000, -0.000000, 128.000000, 32.000000)
	part.RegisterVectorDraw("top-3", drawVector_top_3)
	part.RegisterVectorHitBounds("top-3", -32.000000, -128.000000, 0.000000, 128.000000)
}

func drawVector_coil_off_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -95.000000, -62.000000, -95.000000, 2.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 97.000000, 2.000000, 97.000000, -62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -31.000000, -63.000000, -31.000000, -75.000000, -45.000000, -83.000000, -55.000000, -77.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -55.000000, -77.000000, -60.000000, -74.000000, -63.000000, -68.000000, -63.000000, -62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 1.000000, -63.000000, 1.000000, -75.000000, -13.000000, -83.000000, -23.000000, -76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -23.000000, -76.000000, -28.000000, -74.000000, -31.000000, -68.000000, -31.000000, -62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 32.000000, -63.000000, 32.000000, -75.000000, 19.000000, -83.000000, 8.000000, -76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 8.000000, -76.000000, 3.000000, -74.000000, 0.000000, -68.000000, 1.000000, -62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 64.000000, -63.000000, 64.000000, -75.000000, 51.000000, -83.000000, 40.000000, -76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 40.000000, -76.000000, 35.000000, -74.000000, 32.000000, -68.000000, 33.000000, -62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -63.000000, -63.000000, -75.000000, -77.000000, -82.000000, -87.000000, -76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -87.000000, -76.000000, -92.000000, -74.000000, -95.000000, -68.000000, -95.000000, -62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 97.000000, -63.000000, 97.000000, -75.000000, 83.000000, -83.000000, 73.000000, -76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 73.000000, -76.000000, 68.000000, -74.000000, 65.000000, -68.000000, 65.000000, -62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, -129.000000, -128.000000, 0.000000, 128.000000, 0.000000, 128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_off_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 62.000000, -95.000000, -2.000000, -95.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -2.000000, 97.000000, 62.000000, 97.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, -31.000000, 75.000000, -31.000000, 83.000000, -45.000000, 77.000000, -55.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 77.000000, -55.000000, 74.000000, -60.000000, 68.000000, -63.000000, 62.000000, -63.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 1.000000, 75.000000, 1.000000, 83.000000, -13.000000, 76.000000, -23.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, -23.000000, 74.000000, -28.000000, 68.000000, -31.000000, 62.000000, -31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 32.000000, 75.000000, 32.000000, 83.000000, 19.000000, 76.000000, 8.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, 8.000000, 74.000000, 3.000000, 68.000000, 0.000000, 62.000000, 1.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 64.000000, 75.000000, 64.000000, 83.000000, 51.000000, 76.000000, 40.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, 40.000000, 74.000000, 35.000000, 68.000000, 32.000000, 62.000000, 33.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, -63.000000, 75.000000, -63.000000, 82.000000, -77.000000, 76.000000, -87.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, -87.000000, 74.000000, -92.000000, 68.000000, -95.000000, 62.000000, -95.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 97.000000, 75.000000, 97.000000, 83.000000, 83.000000, 76.000000, 73.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, 73.000000, 74.000000, 68.000000, 68.000000, 65.000000, 62.000000, 65.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{129.000000, -128.000000, -0.000000, -128.000000, -0.000000, 128.000000, 128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_off_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 95.000000, 62.000000, 95.000000, -2.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -97.000000, -2.000000, -97.000000, 62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 31.000000, 63.000000, 31.000000, 75.000000, 45.000000, 83.000000, 55.000000, 77.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 55.000000, 77.000000, 60.000000, 74.000000, 63.000000, 68.000000, 63.000000, 62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -1.000000, 63.000000, -1.000000, 75.000000, 13.000000, 83.000000, 23.000000, 76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 23.000000, 76.000000, 28.000000, 74.000000, 31.000000, 68.000000, 31.000000, 62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -32.000000, 63.000000, -32.000000, 75.000000, -19.000000, 83.000000, -8.000000, 76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -8.000000, 76.000000, -3.000000, 74.000000, -0.000000, 68.000000, -1.000000, 62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -64.000000, 63.000000, -64.000000, 75.000000, -51.000000, 83.000000, -40.000000, 76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -40.000000, 76.000000, -35.000000, 74.000000, -32.000000, 68.000000, -33.000000, 62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 63.000000, 63.000000, 75.000000, 77.000000, 82.000000, 87.000000, 76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 87.000000, 76.000000, 92.000000, 74.000000, 95.000000, 68.000000, 95.000000, 62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -97.000000, 63.000000, -97.000000, 75.000000, -83.000000, 83.000000, -73.000000, 76.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -73.000000, 76.000000, -68.000000, 74.000000, -65.000000, 68.000000, -65.000000, 62.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, 129.000000, 128.000000, -0.000000, -128.000000, -0.000000, -128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_off_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -62.000000, 95.000000, 2.000000, 95.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 2.000000, -97.000000, -62.000000, -97.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, 31.000000, -75.000000, 31.000000, -83.000000, 45.000000, -77.000000, 55.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -77.000000, 55.000000, -74.000000, 60.000000, -68.000000, 63.000000, -62.000000, 63.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -1.000000, -75.000000, -1.000000, -83.000000, 13.000000, -76.000000, 23.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, 23.000000, -74.000000, 28.000000, -68.000000, 31.000000, -62.000000, 31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -32.000000, -75.000000, -32.000000, -83.000000, -19.000000, -76.000000, -8.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, -8.000000, -74.000000, -3.000000, -68.000000, -0.000000, -62.000000, -1.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -64.000000, -75.000000, -64.000000, -83.000000, -51.000000, -76.000000, -40.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, -40.000000, -74.000000, -35.000000, -68.000000, -32.000000, -62.000000, -33.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, 63.000000, -75.000000, 63.000000, -82.000000, 77.000000, -76.000000, 87.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, 87.000000, -74.000000, 92.000000, -68.000000, 95.000000, -62.000000, 95.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -97.000000, -75.000000, -97.000000, -83.000000, -83.000000, -76.000000, -73.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, -73.000000, -74.000000, -68.000000, -68.000000, -65.000000, -62.000000, -65.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-129.000000, 128.000000, 0.000000, 128.000000, 0.000000, -128.000000, -128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_on_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -95.000000, -62.000000, -95.000000, 2.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGLine(ctx, base, 97.000000, 2.000000, 97.000000, -62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -31.000000, -63.000000, -31.000000, -75.000000, -45.000000, -83.000000, -55.000000, -77.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -55.000000, -77.000000, -60.000000, -74.000000, -63.000000, -68.000000, -63.000000, -62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 1.000000, -63.000000, 1.000000, -75.000000, -13.000000, -83.000000, -23.000000, -76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -23.000000, -76.000000, -28.000000, -74.000000, -31.000000, -68.000000, -31.000000, -62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 32.000000, -63.000000, 32.000000, -75.000000, 19.000000, -83.000000, 8.000000, -76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 8.000000, -76.000000, 3.000000, -74.000000, 0.000000, -68.000000, 1.000000, -62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 64.000000, -63.000000, 64.000000, -75.000000, 51.000000, -83.000000, 40.000000, -76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 40.000000, -76.000000, 35.000000, -74.000000, 32.000000, -68.000000, 33.000000, -62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -63.000000, -63.000000, -75.000000, -77.000000, -82.000000, -87.000000, -76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -87.000000, -76.000000, -92.000000, -74.000000, -95.000000, -68.000000, -95.000000, -62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 97.000000, -63.000000, 97.000000, -75.000000, 83.000000, -83.000000, 73.000000, -76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 73.000000, -76.000000, 68.000000, -74.000000, 65.000000, -68.000000, 65.000000, -62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, -129.000000, -128.000000, 0.000000, 128.000000, 0.000000, 128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_on_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 62.000000, -95.000000, -2.000000, -95.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGLine(ctx, base, -2.000000, 97.000000, 62.000000, 97.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, -31.000000, 75.000000, -31.000000, 83.000000, -45.000000, 77.000000, -55.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 77.000000, -55.000000, 74.000000, -60.000000, 68.000000, -63.000000, 62.000000, -63.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 1.000000, 75.000000, 1.000000, 83.000000, -13.000000, 76.000000, -23.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, -23.000000, 74.000000, -28.000000, 68.000000, -31.000000, 62.000000, -31.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 32.000000, 75.000000, 32.000000, 83.000000, 19.000000, 76.000000, 8.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, 8.000000, 74.000000, 3.000000, 68.000000, 0.000000, 62.000000, 1.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 64.000000, 75.000000, 64.000000, 83.000000, 51.000000, 76.000000, 40.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, 40.000000, 74.000000, 35.000000, 68.000000, 32.000000, 62.000000, 33.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, -63.000000, 75.000000, -63.000000, 82.000000, -77.000000, 76.000000, -87.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, -87.000000, 74.000000, -92.000000, 68.000000, -95.000000, 62.000000, -95.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 97.000000, 75.000000, 97.000000, 83.000000, 83.000000, 76.000000, 73.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.000000, 73.000000, 74.000000, 68.000000, 68.000000, 65.000000, 62.000000, 65.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{129.000000, -128.000000, -0.000000, -128.000000, -0.000000, 128.000000, 128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_on_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 95.000000, 62.000000, 95.000000, -2.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGLine(ctx, base, -97.000000, -2.000000, -97.000000, 62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 31.000000, 63.000000, 31.000000, 75.000000, 45.000000, 83.000000, 55.000000, 77.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 55.000000, 77.000000, 60.000000, 74.000000, 63.000000, 68.000000, 63.000000, 62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -1.000000, 63.000000, -1.000000, 75.000000, 13.000000, 83.000000, 23.000000, 76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 23.000000, 76.000000, 28.000000, 74.000000, 31.000000, 68.000000, 31.000000, 62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -32.000000, 63.000000, -32.000000, 75.000000, -19.000000, 83.000000, -8.000000, 76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -8.000000, 76.000000, -3.000000, 74.000000, -0.000000, 68.000000, -1.000000, 62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -64.000000, 63.000000, -64.000000, 75.000000, -51.000000, 83.000000, -40.000000, 76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -40.000000, 76.000000, -35.000000, 74.000000, -32.000000, 68.000000, -33.000000, 62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.000000, 63.000000, 63.000000, 75.000000, 77.000000, 82.000000, 87.000000, 76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 87.000000, 76.000000, 92.000000, 74.000000, 95.000000, 68.000000, 95.000000, 62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -97.000000, 63.000000, -97.000000, 75.000000, -83.000000, 83.000000, -73.000000, 76.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -73.000000, 76.000000, -68.000000, 74.000000, -65.000000, 68.000000, -65.000000, 62.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, 129.000000, 128.000000, -0.000000, -128.000000, -0.000000, -128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_on_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -62.000000, 95.000000, 2.000000, 95.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGLine(ctx, base, 2.000000, -97.000000, -62.000000, -97.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, 31.000000, -75.000000, 31.000000, -83.000000, 45.000000, -77.000000, 55.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -77.000000, 55.000000, -74.000000, 60.000000, -68.000000, 63.000000, -62.000000, 63.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -1.000000, -75.000000, -1.000000, -83.000000, 13.000000, -76.000000, 23.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, 23.000000, -74.000000, 28.000000, -68.000000, 31.000000, -62.000000, 31.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -32.000000, -75.000000, -32.000000, -83.000000, -19.000000, -76.000000, -8.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, -8.000000, -74.000000, -3.000000, -68.000000, -0.000000, -62.000000, -1.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -64.000000, -75.000000, -64.000000, -83.000000, -51.000000, -76.000000, -40.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, -40.000000, -74.000000, -35.000000, -68.000000, -32.000000, -62.000000, -33.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, 63.000000, -75.000000, 63.000000, -82.000000, 77.000000, -76.000000, 87.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, 87.000000, -74.000000, 92.000000, -68.000000, 95.000000, -62.000000, 95.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.000000, -97.000000, -75.000000, -97.000000, -83.000000, -83.000000, -76.000000, -73.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.000000, -73.000000, -74.000000, -68.000000, -68.000000, -65.000000, -62.000000, -65.000000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-129.000000, 128.000000, 0.000000, 128.000000, 0.000000, -128.000000, -128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_flight_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -128.000000, 96.000000, -128.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 128.000000, 96.000000, 128.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.000000, 0.000000, -96.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -80.000000, 0.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -64.000000, -1.000000, 96.000000, -1.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, 64.000000, 64.000000, 64.000000, 64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.000000, 48.000000, 64.000000, 32.000000, 83.000000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, -64.000000, 64.000000, -64.000000, 64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.000000, -48.000000, 64.000000, -32.000000, 83.000000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_flight_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -96.000000, -128.000000, 96.000000, -128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -96.000000, 128.000000, 96.000000, 128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -127.000000, -0.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -0.000000, -80.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 1.000000, -64.000000, 1.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, 128.000000, -64.000000, 64.000000, -32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-48.000000, 47.000000, -32.000000, 64.000000, -48.000000, 83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.000000, 128.000000, 64.000000, 64.000000, 32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{48.000000, 47.000000, 32.000000, 64.000000, 48.000000, 83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_flight_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 128.000000, -96.000000, 128.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -128.000000, -96.000000, -128.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.000000, -0.000000, 96.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 80.000000, -0.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 64.000000, 1.000000, -96.000000, 1.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, -64.000000, -64.000000, -64.000000, -64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.000000, -48.000000, -64.000000, -32.000000, -83.000000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, 64.000000, -64.000000, 64.000000, -64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.000000, 48.000000, -64.000000, 32.000000, -83.000000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_flight_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 96.000000, 128.000000, -96.000000, 128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 96.000000, -128.000000, -96.000000, -128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 127.000000, 0.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 0.000000, 80.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -1.000000, 64.000000, -1.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.000000, -128.000000, 64.000000, -64.000000, 32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{48.000000, -47.000000, 32.000000, -64.000000, 48.000000, -83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, -128.000000, -64.000000, -64.000000, -32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-48.000000, -47.000000, -32.000000, -64.000000, -48.000000, -83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_off_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -128.000000, 96.000000, -128.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 128.000000, 96.000000, 128.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.000000, 0.000000, -96.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -80.000000, 0.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -64.000000, -2.000000, 96.000000, -32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, 64.000000, 64.000000, 64.000000, 64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.000000, 48.000000, 64.000000, 32.000000, 83.000000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, -64.000000, 64.000000, -64.000000, 64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.000000, -48.000000, 64.000000, -32.000000, 83.000000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_off_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -96.000000, -128.000000, 96.000000, -128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -96.000000, 128.000000, 96.000000, 128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -127.000000, -0.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -0.000000, -80.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 2.000000, -64.000000, 32.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, 128.000000, -64.000000, 64.000000, -32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-48.000000, 47.000000, -32.000000, 64.000000, -48.000000, 83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.000000, 128.000000, 64.000000, 64.000000, 32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{48.000000, 47.000000, 32.000000, 64.000000, 48.000000, 83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_off_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 128.000000, -96.000000, 128.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -128.000000, -96.000000, -128.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.000000, -0.000000, 96.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 80.000000, -0.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 64.000000, 2.000000, -96.000000, 32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, -64.000000, -64.000000, -64.000000, -64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.000000, -48.000000, -64.000000, -32.000000, -83.000000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, 64.000000, -64.000000, 64.000000, -64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.000000, 48.000000, -64.000000, 32.000000, -83.000000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_off_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 96.000000, 128.000000, -96.000000, 128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 96.000000, -128.000000, -96.000000, -128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 127.000000, 0.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 0.000000, 80.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -2.000000, 64.000000, -32.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.000000, -128.000000, 64.000000, -64.000000, 32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{48.000000, -47.000000, 32.000000, -64.000000, 48.000000, -83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, -128.000000, -64.000000, -64.000000, -32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-48.000000, -47.000000, -32.000000, -64.000000, -48.000000, -83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_on_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -128.000000, 96.000000, -128.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 128.000000, 96.000000, 128.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.000000, 0.000000, -96.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -80.000000, 0.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -64.000000, -2.000000, 96.000000, 32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, 64.000000, 64.000000, 64.000000, 64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.000000, 48.000000, 64.000000, 32.000000, 83.000000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, -64.000000, 64.000000, -64.000000, 64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.000000, -48.000000, 64.000000, -32.000000, 83.000000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_on_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -96.000000, -128.000000, 96.000000, -128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -96.000000, 128.000000, 96.000000, 128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -127.000000, -0.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -0.000000, -80.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 2.000000, -64.000000, -32.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, 128.000000, -64.000000, 64.000000, -32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-48.000000, 47.000000, -32.000000, 64.000000, -48.000000, 83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.000000, 128.000000, 64.000000, 64.000000, 32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{48.000000, 47.000000, 32.000000, 64.000000, 48.000000, 83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_on_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 128.000000, -96.000000, 128.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -128.000000, -96.000000, -128.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.000000, -0.000000, 96.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 80.000000, -0.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 64.000000, 2.000000, -96.000000, -32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, -64.000000, -64.000000, -64.000000, -64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.000000, -48.000000, -64.000000, -32.000000, -83.000000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, 64.000000, -64.000000, 64.000000, -64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.000000, 48.000000, -64.000000, 32.000000, -83.000000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_on_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 96.000000, 128.000000, -96.000000, 128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 96.000000, -128.000000, -96.000000, -128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 127.000000, 0.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 0.000000, 80.000000, 16.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -2.000000, 64.000000, 32.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.000000, -128.000000, 64.000000, -64.000000, 32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{48.000000, -47.000000, 32.000000, -64.000000, 48.000000, -83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, -128.000000, -64.000000, -64.000000, -32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-48.000000, -47.000000, -32.000000, -64.000000, -48.000000, -83.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_top_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGPolyline(ctx, base, []float64{128.000000, -1.000000, 128.000000, -32.000000, -128.000000, -32.000000, -128.000000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_top_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGPolyline(ctx, base, []float64{1.000000, 128.000000, 32.000000, 128.000000, 32.000000, -128.000000, -0.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_top_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, 1.000000, -128.000000, 32.000000, 128.000000, 32.000000, 128.000000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_top_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGPolyline(ctx, base, []float64{-1.000000, -128.000000, -32.000000, -128.000000, -32.000000, 128.000000, 0.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

