// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Vector names are <stem>-<0..n> from schematic SVGs (underscores → hyphens), excluding toolbar btn_*.svg.
// Without _45: indices 0..3 are quarter-turn steps of the canonical SVG.
// With *-stem_45.svg: indices 0..7 interleave canonical and diagonal art (even idx = canonical, odd = _45); idx/2 is the quarter-turn on that source.
// Each suffix bakes k BasePart.Rotation steps in SVG user space (same convention as core.LocalToWorld); catalog draw passes identity rotation.
package relay

import (
	"coilforge/internal/core"
	"coilforge/internal/part"
	"image/color"
)

const RotationSlots = 4

func init() {
	part.RegisterVectorDraw("coil-off-0", drawVector_coil_off_0)
	part.RegisterPinLayout("coil-off-0", []core.Pt{
		{X:-96.000000, Y:0.000000},
		{X:96.000000, Y:0.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-off-0", -127.945000, -128.556000, 128.000000, 1.649000)
	part.RegisterVectorDraw("coil-off-1", drawVector_coil_off_1)
	part.RegisterPinLayout("coil-off-1", []core.Pt{
		{X:-0.000000, Y:-96.000000},
		{X:-0.000000, Y:96.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-off-1", -1.649000, -127.945000, 128.556000, 128.000000)
	part.RegisterVectorDraw("coil-off-2", drawVector_coil_off_2)
	part.RegisterPinLayout("coil-off-2", []core.Pt{
		{X:96.000000, Y:-0.000000},
		{X:-96.000000, Y:-0.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-off-2", -128.000000, -1.649000, 127.945000, 128.556000)
	part.RegisterVectorDraw("coil-off-3", drawVector_coil_off_3)
	part.RegisterPinLayout("coil-off-3", []core.Pt{
		{X:0.000000, Y:96.000000},
		{X:0.000000, Y:-96.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-off-3", -128.556000, -128.000000, 1.649000, 127.945000)
	part.RegisterVectorDraw("coil-on-0", drawVector_coil_on_0)
	part.RegisterPinLayout("coil-on-0", []core.Pt{
		{X:-96.000000, Y:0.000000},
		{X:96.000000, Y:0.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-on-0", -127.945000, -128.556000, 128.000000, 1.649000)
	part.RegisterVectorDraw("coil-on-1", drawVector_coil_on_1)
	part.RegisterPinLayout("coil-on-1", []core.Pt{
		{X:-0.000000, Y:-96.000000},
		{X:-0.000000, Y:96.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-on-1", -1.649000, -127.945000, 128.556000, 128.000000)
	part.RegisterVectorDraw("coil-on-2", drawVector_coil_on_2)
	part.RegisterPinLayout("coil-on-2", []core.Pt{
		{X:96.000000, Y:-0.000000},
		{X:-96.000000, Y:-0.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-on-2", -128.000000, -1.649000, 127.945000, 128.556000)
	part.RegisterVectorDraw("coil-on-3", drawVector_coil_on_3)
	part.RegisterPinLayout("coil-on-3", []core.Pt{
		{X:0.000000, Y:96.000000},
		{X:0.000000, Y:-96.000000},
	}, []string{
		"CoilA",
		"CoilB",
	})
	part.RegisterVectorHitBounds("coil-on-3", -128.556000, -128.000000, 1.649000, 127.945000)
	part.RegisterVectorDraw("mid-flight-0", drawVector_mid_flight_0)
	part.RegisterPinLayout("mid-flight-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:-64.000000},
		{X:128.000000, Y:64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-flight-0", -128.185000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-flight-1", drawVector_mid_flight_1)
	part.RegisterPinLayout("mid-flight-1", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:64.000000, Y:128.000000},
		{X:-64.000000, Y:128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-flight-1", -96.000000, -128.185000, 96.000000, 128.000000)
	part.RegisterVectorDraw("mid-flight-2", drawVector_mid_flight_2)
	part.RegisterPinLayout("mid-flight-2", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:64.000000},
		{X:-128.000000, Y:-64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-flight-2", -128.000000, -96.000000, 128.185000, 96.000000)
	part.RegisterVectorDraw("mid-flight-3", drawVector_mid_flight_3)
	part.RegisterPinLayout("mid-flight-3", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:-64.000000, Y:-128.000000},
		{X:64.000000, Y:-128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-flight-3", -96.000000, -128.000000, 96.000000, 128.185000)
	part.RegisterVectorDraw("mid-off-0", drawVector_mid_off_0)
	part.RegisterPinLayout("mid-off-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:-64.000000},
		{X:128.000000, Y:64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-off-0", -128.185000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-off-1", drawVector_mid_off_1)
	part.RegisterPinLayout("mid-off-1", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:64.000000, Y:128.000000},
		{X:-64.000000, Y:128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-off-1", -96.000000, -128.185000, 96.000000, 128.000000)
	part.RegisterVectorDraw("mid-off-2", drawVector_mid_off_2)
	part.RegisterPinLayout("mid-off-2", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:64.000000},
		{X:-128.000000, Y:-64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-off-2", -128.000000, -96.000000, 128.185000, 96.000000)
	part.RegisterVectorDraw("mid-off-3", drawVector_mid_off_3)
	part.RegisterPinLayout("mid-off-3", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:-64.000000, Y:-128.000000},
		{X:64.000000, Y:-128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-off-3", -96.000000, -128.000000, 96.000000, 128.185000)
	part.RegisterVectorDraw("mid-on-0", drawVector_mid_on_0)
	part.RegisterPinLayout("mid-on-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:-64.000000},
		{X:128.000000, Y:64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-on-0", -128.185000, -96.000000, 128.000000, 96.000000)
	part.RegisterVectorDraw("mid-on-1", drawVector_mid_on_1)
	part.RegisterPinLayout("mid-on-1", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:64.000000, Y:128.000000},
		{X:-64.000000, Y:128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-on-1", -96.000000, -128.185000, 96.000000, 128.000000)
	part.RegisterVectorDraw("mid-on-2", drawVector_mid_on_2)
	part.RegisterPinLayout("mid-on-2", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:64.000000},
		{X:-128.000000, Y:-64.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-on-2", -128.000000, -96.000000, 128.185000, 96.000000)
	part.RegisterVectorDraw("mid-on-3", drawVector_mid_on_3)
	part.RegisterPinLayout("mid-on-3", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:-64.000000, Y:-128.000000},
		{X:64.000000, Y:-128.000000},
	}, []string{
		"COM",
		"NC",
		"NO",
	})
	part.RegisterVectorHitBounds("mid-on-3", -96.000000, -128.000000, 96.000000, 128.185000)
	part.RegisterVectorDraw("top-0", drawVector_top_0)
	part.RegisterVectorHitBounds("top-0", -127.983750, -32.000000, 128.115500, 0.000000)
	part.RegisterVectorDraw("top-1", drawVector_top_1)
	part.RegisterVectorHitBounds("top-1", -0.000000, -127.983750, 32.000000, 128.115500)
	part.RegisterVectorDraw("top-2", drawVector_top_2)
	part.RegisterVectorHitBounds("top-2", -128.115500, -0.000000, 127.983750, 32.000000)
	part.RegisterVectorDraw("top-3", drawVector_top_3)
	part.RegisterVectorHitBounds("top-3", -32.000000, -128.115500, 0.000000, 127.983750)
}

func drawVector_coil_off_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -95.029500, -62.352000, -95.029500, 1.649000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 96.975000, 1.646000, 96.975000, -62.351000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -31.389000, -62.800000, -31.389000, -74.990000, -44.569000, -82.590000, -55.119000, -76.510000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -55.119000, -76.510000, -60.149000, -73.610000, -63.179000, -68.170000, -63.019000, -62.370000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 0.600000, -62.718000, 0.600000, -74.908000, -12.579000, -82.508000, -23.129000, -76.428000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -23.129000, -76.428000, -28.159000, -73.528000, -31.189000, -68.088000, -31.029000, -62.288000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 32.204000, -62.764000, 32.204000, -74.954000, 19.024000, -82.554000, 8.464000, -76.474000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 8.464000, -76.474000, 3.434000, -73.574000, 0.404000, -68.134000, 0.564000, -62.334000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 64.194000, -62.757000, 64.194000, -74.947000, 51.014000, -82.547000, 40.464000, -76.467000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 40.464000, -76.467000, 35.434000, -73.567000, 32.404000, -68.127000, 32.564000, -62.327000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.369000, -62.695000, -63.369000, -74.885000, -76.559000, -82.485000, -87.099000, -76.405000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -87.099000, -76.405000, -92.129000, -73.505000, -95.159000, -68.065000, -94.999000, -62.265000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 96.568000, -62.759000, 96.568000, -74.949000, 83.388000, -82.549000, 72.838000, -76.469000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 72.838000, -76.469000, 67.808000, -73.569000, 64.778000, -68.129000, 64.938000, -62.329000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-127.890000, -128.556000, -127.945000, 0.000000, 128.000000, 0.000000, 128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_off_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 62.352000, -95.029500, -1.649000, -95.029500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -1.646000, 96.975000, 62.351000, 96.975000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.800000, -31.389000, 74.990000, -31.389000, 82.590000, -44.569000, 76.510000, -55.119000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.510000, -55.119000, 73.610000, -60.149000, 68.170000, -63.179000, 62.370000, -63.019000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.718000, 0.600000, 74.908000, 0.600000, 82.508000, -12.579000, 76.428000, -23.129000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.428000, -23.129000, 73.528000, -28.159000, 68.088000, -31.189000, 62.288000, -31.029000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.764000, 32.204000, 74.954000, 32.204000, 82.554000, 19.024000, 76.474000, 8.464000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.474000, 8.464000, 73.574000, 3.434000, 68.134000, 0.404000, 62.334000, 0.564000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.757000, 64.194000, 74.947000, 64.194000, 82.547000, 51.014000, 76.467000, 40.464000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.467000, 40.464000, 73.567000, 35.434000, 68.127000, 32.404000, 62.327000, 32.564000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.695000, -63.369000, 74.885000, -63.369000, 82.485000, -76.559000, 76.405000, -87.099000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.405000, -87.099000, 73.505000, -92.129000, 68.065000, -95.159000, 62.265000, -94.999000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.759000, 96.568000, 74.949000, 96.568000, 82.549000, 83.388000, 76.469000, 72.838000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.469000, 72.838000, 73.569000, 67.808000, 68.129000, 64.778000, 62.329000, 64.938000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.556000, -127.890000, -0.000000, -127.945000, -0.000000, 128.000000, 128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_off_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 95.029500, 62.352000, 95.029500, -1.649000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -96.975000, -1.646000, -96.975000, 62.351000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 31.389000, 62.800000, 31.389000, 74.990000, 44.569000, 82.590000, 55.119000, 76.510000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 55.119000, 76.510000, 60.149000, 73.610000, 63.179000, 68.170000, 63.019000, 62.370000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -0.600000, 62.718000, -0.600000, 74.908000, 12.579000, 82.508000, 23.129000, 76.428000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 23.129000, 76.428000, 28.159000, 73.528000, 31.189000, 68.088000, 31.029000, 62.288000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -32.204000, 62.764000, -32.204000, 74.954000, -19.024000, 82.554000, -8.464000, 76.474000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -8.464000, 76.474000, -3.434000, 73.574000, -0.404000, 68.134000, -0.564000, 62.334000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -64.194000, 62.757000, -64.194000, 74.947000, -51.014000, 82.547000, -40.464000, 76.467000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -40.464000, 76.467000, -35.434000, 73.567000, -32.404000, 68.127000, -32.564000, 62.327000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.369000, 62.695000, 63.369000, 74.885000, 76.559000, 82.485000, 87.099000, 76.405000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 87.099000, 76.405000, 92.129000, 73.505000, 95.159000, 68.065000, 94.999000, 62.265000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -96.568000, 62.759000, -96.568000, 74.949000, -83.388000, 82.549000, -72.838000, 76.469000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -72.838000, 76.469000, -67.808000, 73.569000, -64.778000, 68.129000, -64.938000, 62.329000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{127.890000, 128.556000, 127.945000, -0.000000, -128.000000, -0.000000, -128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_off_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -62.352000, 95.029500, 1.649000, 95.029500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 1.646000, -96.975000, -62.351000, -96.975000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.800000, 31.389000, -74.990000, 31.389000, -82.590000, 44.569000, -76.510000, 55.119000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.510000, 55.119000, -73.610000, 60.149000, -68.170000, 63.179000, -62.370000, 63.019000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.718000, -0.600000, -74.908000, -0.600000, -82.508000, 12.579000, -76.428000, 23.129000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.428000, 23.129000, -73.528000, 28.159000, -68.088000, 31.189000, -62.288000, 31.029000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.764000, -32.204000, -74.954000, -32.204000, -82.554000, -19.024000, -76.474000, -8.464000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.474000, -8.464000, -73.574000, -3.434000, -68.134000, -0.404000, -62.334000, -0.564000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.757000, -64.194000, -74.947000, -64.194000, -82.547000, -51.014000, -76.467000, -40.464000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.467000, -40.464000, -73.567000, -35.434000, -68.127000, -32.404000, -62.327000, -32.564000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.695000, 63.369000, -74.885000, 63.369000, -82.485000, 76.559000, -76.405000, 87.099000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.405000, 87.099000, -73.505000, 92.129000, -68.065000, 95.159000, -62.265000, 94.999000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.759000, -96.568000, -74.949000, -96.568000, -82.549000, -83.388000, -76.469000, -72.838000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.469000, -72.838000, -73.569000, -67.808000, -68.129000, -64.778000, -62.329000, -64.938000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.556000, 127.890000, 0.000000, 127.945000, 0.000000, -128.000000, -128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_on_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -95.029500, -62.352000, -95.029500, 1.649000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGLine(ctx, base, 96.975000, 1.646000, 96.975000, -62.351000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -31.389000, -62.800000, -31.389000, -74.990000, -44.569000, -82.590000, -55.119000, -76.510000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -55.119000, -76.510000, -60.149000, -73.610000, -63.179000, -68.170000, -63.019000, -62.370000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 0.600000, -62.718000, 0.600000, -74.908000, -12.579000, -82.508000, -23.129000, -76.428000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -23.129000, -76.428000, -28.159000, -73.528000, -31.189000, -68.088000, -31.029000, -62.288000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 32.204000, -62.764000, 32.204000, -74.954000, 19.024000, -82.554000, 8.464000, -76.474000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 8.464000, -76.474000, 3.434000, -73.574000, 0.404000, -68.134000, 0.564000, -62.334000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 64.194000, -62.757000, 64.194000, -74.947000, 51.014000, -82.547000, 40.464000, -76.467000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 40.464000, -76.467000, 35.434000, -73.567000, 32.404000, -68.127000, 32.564000, -62.327000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -63.369000, -62.695000, -63.369000, -74.885000, -76.559000, -82.485000, -87.099000, -76.405000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -87.099000, -76.405000, -92.129000, -73.505000, -95.159000, -68.065000, -94.999000, -62.265000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 96.568000, -62.759000, 96.568000, -74.949000, 83.388000, -82.549000, 72.838000, -76.469000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 72.838000, -76.469000, 67.808000, -73.569000, 64.778000, -68.129000, 64.938000, -62.329000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-127.890000, -128.556000, -127.945000, 0.000000, 128.000000, 0.000000, 128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_on_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 62.352000, -95.029500, -1.649000, -95.029500, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGLine(ctx, base, -1.646000, 96.975000, 62.351000, 96.975000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.800000, -31.389000, 74.990000, -31.389000, 82.590000, -44.569000, 76.510000, -55.119000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.510000, -55.119000, 73.610000, -60.149000, 68.170000, -63.179000, 62.370000, -63.019000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.718000, 0.600000, 74.908000, 0.600000, 82.508000, -12.579000, 76.428000, -23.129000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.428000, -23.129000, 73.528000, -28.159000, 68.088000, -31.189000, 62.288000, -31.029000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.764000, 32.204000, 74.954000, 32.204000, 82.554000, 19.024000, 76.474000, 8.464000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.474000, 8.464000, 73.574000, 3.434000, 68.134000, 0.404000, 62.334000, 0.564000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.757000, 64.194000, 74.947000, 64.194000, 82.547000, 51.014000, 76.467000, 40.464000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.467000, 40.464000, 73.567000, 35.434000, 68.127000, 32.404000, 62.327000, 32.564000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.695000, -63.369000, 74.885000, -63.369000, 82.485000, -76.559000, 76.405000, -87.099000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.405000, -87.099000, 73.505000, -92.129000, 68.065000, -95.159000, 62.265000, -94.999000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 62.759000, 96.568000, 74.949000, 96.568000, 82.549000, 83.388000, 76.469000, 72.838000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 76.469000, 72.838000, 73.569000, 67.808000, 68.129000, 64.778000, 62.329000, 64.938000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.556000, -127.890000, -0.000000, -127.945000, -0.000000, 128.000000, 128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_on_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 95.029500, 62.352000, 95.029500, -1.649000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGLine(ctx, base, -96.975000, -1.646000, -96.975000, 62.351000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 31.389000, 62.800000, 31.389000, 74.990000, 44.569000, 82.590000, 55.119000, 76.510000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 55.119000, 76.510000, 60.149000, 73.610000, 63.179000, 68.170000, 63.019000, 62.370000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -0.600000, 62.718000, -0.600000, 74.908000, 12.579000, 82.508000, 23.129000, 76.428000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 23.129000, 76.428000, 28.159000, 73.528000, 31.189000, 68.088000, 31.029000, 62.288000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -32.204000, 62.764000, -32.204000, 74.954000, -19.024000, 82.554000, -8.464000, 76.474000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -8.464000, 76.474000, -3.434000, 73.574000, -0.404000, 68.134000, -0.564000, 62.334000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -64.194000, 62.757000, -64.194000, 74.947000, -51.014000, 82.547000, -40.464000, 76.467000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -40.464000, 76.467000, -35.434000, 73.567000, -32.404000, 68.127000, -32.564000, 62.327000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 63.369000, 62.695000, 63.369000, 74.885000, 76.559000, 82.485000, 87.099000, 76.405000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, 87.099000, 76.405000, 92.129000, 73.505000, 95.159000, 68.065000, 94.999000, 62.265000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -96.568000, 62.759000, -96.568000, 74.949000, -83.388000, 82.549000, -72.838000, 76.469000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -72.838000, 76.469000, -67.808000, 73.569000, -64.778000, 68.129000, -64.938000, 62.329000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{127.890000, 128.556000, 127.945000, -0.000000, -128.000000, -0.000000, -128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_coil_on_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -62.352000, 95.029500, 1.649000, 95.029500, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGLine(ctx, base, 1.646000, -96.975000, -62.351000, -96.975000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.800000, 31.389000, -74.990000, 31.389000, -82.590000, 44.569000, -76.510000, 55.119000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.510000, 55.119000, -73.610000, 60.149000, -68.170000, 63.179000, -62.370000, 63.019000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.718000, -0.600000, -74.908000, -0.600000, -82.508000, 12.579000, -76.428000, 23.129000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.428000, 23.129000, -73.528000, 28.159000, -68.088000, 31.189000, -62.288000, 31.029000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.764000, -32.204000, -74.954000, -32.204000, -82.554000, -19.024000, -76.474000, -8.464000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.474000, -8.464000, -73.574000, -3.434000, -68.134000, -0.404000, -62.334000, -0.564000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.757000, -64.194000, -74.947000, -64.194000, -82.547000, -51.014000, -76.467000, -40.464000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.467000, -40.464000, -73.567000, -35.434000, -68.127000, -32.404000, -62.327000, -32.564000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.695000, 63.369000, -74.885000, 63.369000, -82.485000, 76.559000, -76.405000, 87.099000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.405000, 87.099000, -73.505000, 92.129000, -68.065000, 95.159000, -62.265000, 94.999000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -62.759000, -96.568000, -74.949000, -96.568000, -82.549000, -83.388000, -76.469000, -72.838000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGCubicBezier(ctx, base, -76.469000, -72.838000, -73.569000, -67.808000, -68.129000, -64.778000, -62.329000, -64.938000, 10.000000, color.RGBA{R:255, G:172, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.556000, 127.890000, 0.000000, 127.945000, 0.000000, -128.000000, -128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_flight_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -128.185000, 96.000000, -128.185000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.701500, 96.000000, 127.701500, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.380000, 0.000000, -96.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -80.171000, 0.000000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -64.112000, -0.805500, 95.999000, -0.805500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{127.663000, 63.987000, 64.000000, 63.993500, 64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{46.533000, 47.823000, 64.000000, 32.000000, 82.905000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, -63.987000, 64.337000, -63.993500, 64.337000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{46.870000, -47.823000, 64.337000, -32.000000, 83.242000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_flight_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -96.000000, -128.185000, 96.000000, -128.185000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -96.000000, 127.701500, 96.000000, 127.701500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -127.380000, -0.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -0.000000, -80.171000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 0.805500, -64.112000, 0.805500, 95.999000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-63.987000, 127.663000, -63.993500, 64.000000, -32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.823000, 46.533000, -32.000000, 64.000000, -48.000000, 82.905000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{63.987000, 128.000000, 63.993500, 64.337000, 32.000000, 64.337000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.823000, 46.870000, 32.000000, 64.337000, 48.000000, 83.242000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_flight_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 128.185000, -96.000000, 128.185000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.701500, -96.000000, -127.701500, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.380000, -0.000000, 96.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 80.171000, -0.000000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 64.112000, 0.805500, -95.999000, 0.805500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-127.663000, -63.987000, -64.000000, -63.993500, -64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-46.533000, -47.823000, -64.000000, -32.000000, -82.905000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, 63.987000, -64.337000, 63.993500, -64.337000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-46.870000, 47.823000, -64.337000, 32.000000, -83.242000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_flight_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 96.000000, 128.185000, -96.000000, 128.185000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 96.000000, -127.701500, -96.000000, -127.701500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 127.380000, 0.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 0.000000, 80.171000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -0.805500, 64.112000, -0.805500, -95.999000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{63.987000, -127.663000, 63.993500, -64.000000, 32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.823000, -46.533000, 32.000000, -64.000000, 48.000000, -82.905000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-63.987000, -128.000000, -63.993500, -64.337000, -32.000000, -64.337000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.823000, -46.870000, -32.000000, -64.337000, -48.000000, -83.242000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_off_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -128.185000, 96.000000, -128.185000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.701500, 96.000000, 127.701500, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.380000, 0.000000, -96.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -80.171000, 0.000000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -64.112000, -1.611000, 95.831000, -32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{127.663000, 63.987000, 64.000000, 63.993500, 64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{46.533000, 47.823000, 64.000000, 32.000000, 82.905000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, -63.987000, 64.337000, -63.993500, 64.337000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{46.870000, -47.823000, 64.337000, -32.000000, 83.242000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_off_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -96.000000, -128.185000, 96.000000, -128.185000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -96.000000, 127.701500, 96.000000, 127.701500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -127.380000, -0.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -0.000000, -80.171000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 1.611000, -64.112000, 32.000000, 95.831000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-63.987000, 127.663000, -63.993500, 64.000000, -32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.823000, 46.533000, -32.000000, 64.000000, -48.000000, 82.905000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{63.987000, 128.000000, 63.993500, 64.337000, 32.000000, 64.337000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.823000, 46.870000, 32.000000, 64.337000, 48.000000, 83.242000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_off_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 128.185000, -96.000000, 128.185000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.701500, -96.000000, -127.701500, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.380000, -0.000000, 96.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 80.171000, -0.000000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 64.112000, 1.611000, -95.831000, 32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-127.663000, -63.987000, -64.000000, -63.993500, -64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-46.533000, -47.823000, -64.000000, -32.000000, -82.905000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, 63.987000, -64.337000, 63.993500, -64.337000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-46.870000, 47.823000, -64.337000, 32.000000, -83.242000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_off_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 96.000000, 128.185000, -96.000000, 128.185000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 96.000000, -127.701500, -96.000000, -127.701500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 127.380000, 0.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 0.000000, 80.171000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -1.611000, 64.112000, -32.000000, -95.831000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{63.987000, -127.663000, 63.993500, -64.000000, 32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.823000, -46.533000, 32.000000, -64.000000, 48.000000, -82.905000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-63.987000, -128.000000, -63.993500, -64.337000, -32.000000, -64.337000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.823000, -46.870000, -32.000000, -64.337000, -48.000000, -83.242000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_on_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -128.185000, 96.000000, -128.185000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.701500, 96.000000, 127.701500, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.380000, 0.000000, -96.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -80.171000, 0.000000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -64.112000, -1.611000, 95.831000, 32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{127.663000, 63.987000, 64.000000, 63.993500, 64.000000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{46.533000, 47.823000, 64.000000, 32.000000, 82.905000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.000000, -63.987000, 64.337000, -63.993500, 64.337000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{46.870000, -47.823000, 64.337000, -32.000000, 83.242000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_on_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -96.000000, -128.185000, 96.000000, -128.185000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -96.000000, 127.701500, 96.000000, 127.701500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -127.380000, -0.000000, -96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, -0.000000, -80.171000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 1.611000, -64.112000, -32.000000, 95.831000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-63.987000, 127.663000, -63.993500, 64.000000, -32.000000, 64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.823000, 46.533000, -32.000000, 64.000000, -48.000000, 82.905000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{63.987000, 128.000000, 63.993500, 64.337000, 32.000000, 64.337000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.823000, 46.870000, 32.000000, 64.337000, 48.000000, 83.242000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_on_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 128.185000, -96.000000, 128.185000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -127.701500, -96.000000, -127.701500, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 127.380000, -0.000000, 96.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 80.171000, -0.000000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 64.112000, 1.611000, -95.831000, -32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-127.663000, -63.987000, -64.000000, -63.993500, -64.000000, -32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-46.533000, -47.823000, -64.000000, -32.000000, -82.905000, -48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.000000, 63.987000, -64.337000, 63.993500, -64.337000, 32.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-46.870000, 47.823000, -64.337000, 32.000000, -83.242000, 48.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_mid_on_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 96.000000, 128.185000, -96.000000, 128.185000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 96.000000, -127.701500, -96.000000, -127.701500, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 127.380000, 0.000000, 96.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGCircle(ctx, base, 0.000000, 80.171000, 16.058000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -1.611000, 64.112000, 32.000000, -95.831000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{63.987000, -127.663000, 63.993500, -64.000000, 32.000000, -64.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{47.823000, -46.533000, 32.000000, -64.000000, 48.000000, -82.905000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-63.987000, -128.000000, -63.993500, -64.337000, -32.000000, -64.337000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-47.823000, -46.870000, -32.000000, -64.337000, -48.000000, -83.242000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_top_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGPolyline(ctx, base, []float64{128.115500, -0.564000, 128.057750, -32.000000, -127.983750, -32.000000, -127.782500, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_top_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGPolyline(ctx, base, []float64{0.564000, 128.115500, 32.000000, 128.057750, 32.000000, -127.983750, -0.000000, -127.782500}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_top_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGPolyline(ctx, base, []float64{-128.115500, 0.564000, -128.057750, 32.000000, 127.983750, 32.000000, 127.782500, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_top_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGPolyline(ctx, base, []float64{-0.564000, -128.115500, -32.000000, -128.057750, -32.000000, 127.983750, 0.000000, 127.782500}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

