// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Pin fields match red authoring circle id attributes in catalog SVGs (see vectors_gen.go RegisterPinLayout).

package diode

import "coilforge/internal/core"

// DiodePinIDs holds stable pin identity for this catalog type.
type DiodePinIDs struct {
	ANODE core.PinID `json:"aNODE"`
	CATHODE core.PinID `json:"cATHODE"`
}

// diodePinMarkerMap maps SVG marker ids from the vector layout to pin IDs for anchor placement.
func diodePinMarkerMap(self *Diode) map[string]core.PinID {
	return map[string]core.PinID{
		"ANODE": self.ANODE,
		"CATHODE": self.CATHODE,
	}
}

// assignNewDiodePins allocates fresh pin IDs (e.g. clone).
func assignNewDiodePins(self *Diode, alloc func() core.PinID) {
	self.ANODE = alloc()
	self.CATHODE = alloc()
}
