// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Pin fields match red authoring circle id attributes in catalog SVGs (see vectors_gen.go RegisterPinLayout).

package gnd

import "coilforge/internal/core"

// GndPinIDs holds stable pin identity for this catalog type.
type GndPinIDs struct {
	GND core.PinID `json:"gND"`
}

// gndPinMarkerMap maps SVG marker ids from the vector layout to pin IDs for anchor placement.
func gndPinMarkerMap(self *Gnd) map[string]core.PinID {
	return map[string]core.PinID{
		"GND": self.GND,
	}
}

// assignNewGndPins allocates fresh pin IDs (e.g. clone).
func assignNewGndPins(self *Gnd, alloc func() core.PinID) {
	self.GND = alloc()
}
