// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Vector names are <stem>-<0..n> from schematic SVGs (underscores → hyphens), excluding toolbar btn_*.svg.
// Without _45: indices 0..3 are quarter-turn steps of the canonical SVG.
// With *-stem_45.svg: indices 0..7 interleave canonical and diagonal art (even idx = canonical, odd = _45); idx/2 is the quarter-turn on that source.
// Each suffix bakes k BasePart.Rotation steps in SVG user space (same convention as core.LocalToWorld); catalog draw passes identity rotation.
package gnd

import (
	"coilforge/internal/core"
	"coilforge/internal/part"
	"image/color"
)

const RotationSlots = 4

func init() {
	part.RegisterVectorDraw("gnd-0", drawVector_gnd_0)
	part.RegisterPinLayout("gnd-0", []core.Pt{
		{X:0.000000, Y:0.000000},
	}, []string{
		"GND",
	})
	part.RegisterVectorHitBounds("gnd-0", -64.000000, -0.000000, 64.000000, 109.000000)
	part.RegisterVectorDraw("gnd-1", drawVector_gnd_1)
	part.RegisterPinLayout("gnd-1", []core.Pt{
		{X:-0.000000, Y:0.000000},
	}, []string{
		"GND",
	})
	part.RegisterVectorHitBounds("gnd-1", -109.000000, -64.000000, 0.000000, 64.000000)
	part.RegisterVectorDraw("gnd-2", drawVector_gnd_2)
	part.RegisterPinLayout("gnd-2", []core.Pt{
		{X:-0.000000, Y:-0.000000},
	}, []string{
		"GND",
	})
	part.RegisterVectorHitBounds("gnd-2", -64.000000, -109.000000, 64.000000, 0.000000)
	part.RegisterVectorDraw("gnd-3", drawVector_gnd_3)
	part.RegisterPinLayout("gnd-3", []core.Pt{
		{X:0.000000, Y:-0.000000},
	}, []string{
		"GND",
	})
	part.RegisterVectorHitBounds("gnd-3", -0.000000, -64.000000, 109.000000, 64.000000)
}

func drawVector_gnd_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -64.000000, 64.000000, 64.000000, 64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -31.000000, 86.000000, 32.000000, 86.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -10.000000, 109.000000, 10.000000, 109.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 64.000000, 0.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_gnd_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -64.000000, -64.000000, -64.000000, 64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -86.000000, -31.000000, -86.000000, 32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -109.000000, -10.000000, -109.000000, 10.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -64.000000, 0.000000, 0.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_gnd_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 64.000000, -64.000000, -64.000000, -64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 31.000000, -86.000000, -32.000000, -86.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 10.000000, -109.000000, -10.000000, -109.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -64.000000, -0.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_gnd_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 64.000000, 64.000000, 64.000000, -64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 86.000000, 31.000000, 86.000000, -32.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 109.000000, 10.000000, 109.000000, -10.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 64.000000, -0.000000, -0.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

