// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Pin fields match red authoring circle id attributes in catalog SVGs (see vectors_gen.go RegisterPinLayout).

package clock

import "coilforge/internal/core"

// ClockPinIDs holds stable pin identity for this catalog type.
type ClockPinIDs struct {
	CLK core.PinID `json:"cLK"`
}

// clockPinMarkerMap maps SVG marker ids from the vector layout to pin IDs for anchor placement.
func clockPinMarkerMap(self *Clock) map[string]core.PinID {
	return map[string]core.PinID{
		"CLK": self.CLK,
	}
}

// assignNewClockPins allocates fresh pin IDs (e.g. clone).
func assignNewClockPins(self *Clock, alloc func() core.PinID) {
	self.CLK = alloc()
}
