// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Vector names are <stem>-<0..n> from schematic SVGs (underscores → hyphens), excluding toolbar btn_*.svg.
// Without _45: indices 0..3 are quarter-turn steps of the canonical SVG.
// With *-stem_45.svg: indices 0..7 interleave canonical and diagonal art (even idx = canonical, odd = _45); idx/2 is the quarter-turn on that source.
// Each suffix bakes k BasePart.Rotation steps in SVG user space (same convention as core.LocalToWorld); catalog draw passes identity rotation.
package clock

import (
	"coilforge/internal/core"
	"coilforge/internal/part"
	"image/color"
)

const RotationSlots = 4

func init() {
	part.RegisterVectorDraw("clock-0", drawVector_clock_0)
	part.RegisterPinLayout("clock-0", []core.Pt{
		{X:0.000000, Y:64.000000},
	}, []string{
		"CLK",
	})
	part.RegisterVectorHitBounds("clock-0", -64.000000, -128.000000, 64.000000, 64.000000)
	part.RegisterVectorDraw("clock-1", drawVector_clock_1)
	part.RegisterPinLayout("clock-1", []core.Pt{
		{X:-64.000000, Y:0.000000},
	}, []string{
		"CLK",
	})
	part.RegisterVectorHitBounds("clock-1", -64.000000, -64.000000, 128.000000, 64.000000)
	part.RegisterVectorDraw("clock-2", drawVector_clock_2)
	part.RegisterPinLayout("clock-2", []core.Pt{
		{X:-0.000000, Y:-64.000000},
	}, []string{
		"CLK",
	})
	part.RegisterVectorHitBounds("clock-2", -64.000000, -64.000000, 64.000000, 128.000000)
	part.RegisterVectorDraw("clock-3", drawVector_clock_3)
	part.RegisterPinLayout("clock-3", []core.Pt{
		{X:64.000000, Y:-0.000000},
	}, []string{
		"CLK",
	})
	part.RegisterVectorHitBounds("clock-3", -128.000000, -64.000000, 64.000000, 64.000000)
}

func drawVector_clock_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGRoundedRect(ctx, base, -64.000000, -128.000000, 128.000000, 128.000000, 20.000000, 20.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 0.000000, 0.000000, 0.000000, 64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -16.000000, -44.000000, -16.000000, -84.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 16.000000, -44.000000, 16.000000, -84.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -21.000000, -84.000000, 21.000000, -84.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -40.000000, -49.000000, -11.000000, -49.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 11.000000, -49.000000, 40.000000, -49.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_clock_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGRoundedRect(ctx, base, -0.000000, -64.000000, 128.000000, 128.000000, 20.000000, 20.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -0.000000, 0.000000, -64.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 44.000000, -16.000000, 84.000000, -16.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 44.000000, 16.000000, 84.000000, 16.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 84.000000, -21.000000, 84.000000, 21.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 49.000000, -40.000000, 49.000000, -11.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 49.000000, 11.000000, 49.000000, 40.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_clock_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGRoundedRect(ctx, base, -64.000000, -0.000000, 128.000000, 128.000000, 20.000000, 20.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, -0.000000, -0.000000, -0.000000, -64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 16.000000, 44.000000, 16.000000, 84.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -16.000000, 44.000000, -16.000000, 84.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 21.000000, 84.000000, -21.000000, 84.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 40.000000, 49.000000, 11.000000, 49.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -11.000000, 49.000000, -40.000000, 49.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_clock_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGRoundedRect(ctx, base, -128.000000, -64.000000, 128.000000, 128.000000, 20.000000, 20.000000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGLine(ctx, base, 0.000000, -0.000000, 64.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -44.000000, 16.000000, -84.000000, 16.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -44.000000, -16.000000, -84.000000, -16.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -84.000000, 21.000000, -84.000000, -21.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -49.000000, 40.000000, -49.000000, 11.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -49.000000, -11.000000, -49.000000, -40.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

