//go:build genpartvectors

package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/image/colornames"
)

type primitiveKind int

const (
	primLine primitiveKind = iota
	primPolyline
	primRect
	primCircle
)

type primitive struct {
	Kind        primitiveKind
	Points      []float64
	Closed      bool
	X           float64
	Y           float64
	W           float64
	H           float64
	Rx          float64
	Ry          float64
	CX          float64
	CY          float64
	R           float64
	StrokeWidth float64
	Stroke      string
	Fill        string
	HasStroke   bool
	HasFill     bool
	ElemID      string // XML id on primitive (circles carry pin authoring ids).
}

type svgAsset struct {
	ViewMinX float64 // viewBox min-x (often 0; negative when symbol is centered on origin).
	ViewMinY float64
	ViewW    float64
	ViewH    float64
	Prims    []primitive
}

// svgPinCenter is the center of a red (#FF0000) authoring pin marker circle in SVG user units.
type svgPinCenter struct {
	CX, CY float64
	ID     string // circle/ellipse id attribute; empty if unset.
}

func catAssetsRel(pkg string) string {
	return filepath.Join("internal", "part", "catalog", pkg, "assets")
}

// schematic45Suffix marks optional paired diagonal art: foo_45.svg augments foo.svg with indices 4..7.
const schematic45Suffix = "_45"

type logicalSVG struct {
	Name      string // registry vector stem, e.g. indicator-off
	CanonPath string
	Path45    string // optional; empty when no *_45.svg companion
}

func main() {
	if len(os.Args) != 2 {
		fail("usage: go run -tags genpartvectors ./scripts/gen_part_vectors.go <catalog-package>")
	}
	pkg := os.Args[1]
	if pkg == "" || pkg == "." || strings.Contains(pkg, "..") || strings.Contains(pkg, "/") || strings.Contains(pkg, "\\") {
		fail("invalid catalog package name %q", pkg)
	}

	root, err := os.Getwd()
	if err != nil {
		fail("cwd: %v", err)
	}
	assetsDir := filepath.Join(root, catAssetsRel(pkg))
	logical, err := discoverLogicalSVGs(assetsDir)
	if err != nil {
		fail("discover: %v", err)
	}
	if len(logical) == 0 {
		fail("no schematic SVG files in %s (expect *.svg excluding btn_*.svg)", assetsDir)
	}

	type loaded struct {
		name    string
		asset   svgAsset
		asset45 svgAsset
		pins    []svgPinCenter
		pins45  []svgPinCenter
		has45   bool
	}
	var loadedAssets []loaded
	for _, lg := range logical {
		relCanon, _ := filepath.Rel(root, lg.CanonPath)
		asset, pins, err := loadVectorSVG(lg.CanonPath)
		if err != nil {
			fail("load %s: %v", relCanon, err)
		}
		entry := loaded{name: lg.Name, asset: asset, pins: pins, has45: lg.Path45 != ""}
		if lg.Path45 != "" {
			rel45, _ := filepath.Rel(root, lg.Path45)
			a45, p45, err := loadVectorSVG(lg.Path45)
			if err != nil {
				fail("load %s: %v", rel45, err)
			}
			entry.asset45 = a45
			entry.pins45 = p45
		}
		loadedAssets = append(loadedAssets, entry)
	}
	sort.Slice(loadedAssets, func(i, j int) bool { return loadedAssets[i].name < loadedAssets[j].name })

	rotationSlots := 4
	slotKinds := map[int]struct{}{}
	for _, L := range loadedAssets {
		n := 4
		if L.has45 {
			n = 8
		}
		slotKinds[n] = struct{}{}
		if len(slotKinds) > 1 {
			fail("mixed %s coverage in package %s: give every schematic stem a matching *%s.svg or omit diagonals for all",
				schematic45Suffix, pkg, schematic45Suffix)
		}
		if L.has45 {
			rotationSlots = 8
		}
	}

	outPath := filepath.Join(root, "internal", "part", "catalog", pkg, "vectors_gen.go")

	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.\n")
	buf.WriteString("// Vector names are <stem>-<0..n> from schematic SVGs (underscores → hyphens), excluding toolbar btn_*.svg.\n")
	buf.WriteString("// Without _45: indices 0..3 are quarter-turn steps of the canonical SVG.\n")
	buf.WriteString("// With *-stem_45.svg: indices 0..7 interleave canonical and diagonal art (even idx = canonical, odd = _45); idx/2 is the quarter-turn on that source.\n")
	buf.WriteString("// Each suffix bakes k BasePart.Rotation steps in SVG user space (same convention as core.LocalToWorld); catalog draw passes identity rotation.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	buf.WriteString("import (\n")
	buf.WriteString("\t\"coilforge/internal/core\"\n")
	buf.WriteString("\t\"coilforge/internal/part\"\n")
	buf.WriteString("\t\"image/color\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString(fmt.Sprintf("const RotationSlots = %d\n\n", rotationSlots))

	buf.WriteString("func init() {\n")
	for _, L := range loadedAssets {
		maxIdx := 4
		if L.has45 {
			maxIdx = 8
		}
		for idx := 0; idx < maxIdx; idx++ {
			vecName := fmt.Sprintf("%s-%d", L.name, idx)
			asset, pins := interleavedBakedAsset(L.asset, L.pins, L.asset45, L.pins45, L.has45, idx)
			fn := goDrawFuncName(vecName)
			buf.WriteString(fmt.Sprintf("\tpart.RegisterVectorDraw(%q, %s)\n", vecName, fn))
			emitRegisterPinLayout(&buf, vecName, pins)
			minX, minY, maxX, maxY, ok := computeGeomBBox(asset.Prims)
			if !ok {
				fail("no drawable geometry for vector %q", vecName)
			}
			emitRegisterHitBounds(&buf, vecName, minX, minY, maxX, maxY)
		}
	}
	buf.WriteString("}\n\n")

	for _, L := range loadedAssets {
		maxIdx := 4
		if L.has45 {
			maxIdx = 8
		}
		for idx := 0; idx < maxIdx; idx++ {
			vecName := fmt.Sprintf("%s-%d", L.name, idx)
			fn := goDrawFuncName(vecName)
			asset, _ := interleavedBakedAsset(L.asset, L.pins, L.asset45, L.pins45, L.has45, idx)
			buf.WriteString(fmt.Sprintf("func %s(ctx part.DrawContext, base core.BasePart) bool {\n", fn))
			emitDrawPrimitives(&buf, asset)
			buf.WriteString("\treturn true\n}\n\n")
		}
	}

	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fail("write generated file: %v", err)
	}
}

// interleavedBakedAsset picks canonical vs *_45 geometry for global rotation index idx.
// Without _45: idx is only 0..3 — quarter-turn steps on the canonical SVG.
// With _45: idx is 0..7 — even idx uses canonical, odd idx uses _45; idx/2 is the quarter-turn on that source (45° steps overall).
func interleavedBakedAsset(asset svgAsset, pins []svgPinCenter, asset45 svgAsset, pins45 []svgPinCenter, has45 bool, idx int) (svgAsset, []svgPinCenter) {
	if !has45 {
		return rotateAssetPrimitives(asset, idx), rotatePinCenters(pins, idx)
	}
	k := idx / 2
	if idx%2 == 0 {
		return rotateAssetPrimitives(asset, k), rotatePinCenters(pins, k)
	}
	return rotateAssetPrimitives(asset45, k), rotatePinCenters(pins45, k)
}

func discoverLogicalSVGs(assetsDir string) ([]logicalSVG, error) {
	entries, err := os.ReadDir(assetsDir)
	if err != nil {
		return nil, err
	}
	canon := map[string]string{}
	forty := map[string]string{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.EqualFold(filepath.Ext(name), ".svg") {
			continue
		}
		if strings.HasPrefix(strings.ToLower(name), "btn_") {
			continue
		}
		stem := strings.TrimSuffix(name, filepath.Ext(name))
		path := filepath.Join(assetsDir, name)
		lower := strings.ToLower(stem)
		if strings.HasSuffix(lower, schematic45Suffix) && len(stem) > len(schematic45Suffix) {
			baseStem := stem[:len(stem)-len(schematic45Suffix)]
			forty[baseStem] = path
			continue
		}
		canon[stem] = path
	}
	var stems []string
	for s := range canon {
		stems = append(stems, s)
	}
	sort.Strings(stems)
	var out []logicalSVG
	for _, stem := range stems {
		p45 := forty[stem]
		delete(forty, stem)
		out = append(out, logicalSVG{
			Name:      vectorNameFromStem(stem),
			CanonPath: canon[stem],
			Path45:    p45,
		})
	}
	for stem := range forty {
		return nil, fmt.Errorf("orphan diagonal SVG %q%s.svg without matching base schematic %q.svg", stem, schematic45Suffix, stem)
	}
	return out, nil
}

func vectorNameFromStem(stem string) string {
	return strings.ReplaceAll(strings.ToLower(stem), "_", "-")
}

func vectorNameFromSVGFile(filename string) string {
	stem := strings.TrimSuffix(filename, filepath.Ext(filename))
	return vectorNameFromStem(stem)
}

func goDrawFuncName(vectorName string) string {
	safe := strings.ReplaceAll(vectorName, "-", "_")
	return "drawVector_" + safe
}

func emitRegisterPinLayout(buf *bytes.Buffer, name string, pins []svgPinCenter) {
	if len(pins) == 0 {
		return
	}
	allEmptyIDs := true
	for _, p := range pins {
		if p.ID != "" {
			allEmptyIDs = false
			break
		}
	}
	buf.WriteString(fmt.Sprintf("\tpart.RegisterPinLayout(%q, []core.Pt{\n", name))
	for _, p := range pins {
		buf.WriteString(fmt.Sprintf("\t\t{X:%.6f, Y:%.6f},\n", p.CX, p.CY))
	}
	buf.WriteString("\t}")
	if allEmptyIDs {
		buf.WriteString(", nil)\n")
	} else {
		buf.WriteString(", []string{\n")
		for _, p := range pins {
			buf.WriteString(fmt.Sprintf("\t\t%q,\n", p.ID))
		}
		buf.WriteString("\t})\n")
	}
}

func emitRegisterHitBounds(buf *bytes.Buffer, name string, minX, minY, maxX, maxY float64) {
	buf.WriteString(fmt.Sprintf("\tpart.RegisterVectorHitBounds(%q, %.6f, %.6f, %.6f, %.6f)\n", name, minX, minY, maxX, maxY))
}

func validateCenteredViewBox(minX, minY, vw, vh float64, path string) {
	if vw <= 0 || vh <= 0 {
		return
	}
	cx := minX + vw/2
	cy := minY + vh/2
	const eps = 1e-2
	if math.Abs(cx) > eps || math.Abs(cy) > eps {
		fail("%s: SVG viewBox must be centered on symbol origin (minX+width/2 == 0 and minY+height/2 == 0); got center (%.6f, %.6f)", path, cx, cy)
	}
}

func computeGeomBBox(prims []primitive) (minX, minY, maxX, maxY float64, has bool) {
	grow := func(x, y float64) {
		if !has {
			minX, maxX = x, x
			minY, maxY = y, y
			has = true
			return
		}
		if x < minX {
			minX = x
		}
		if x > maxX {
			maxX = x
		}
		if y < minY {
			minY = y
		}
		if y > maxY {
			maxY = y
		}
	}
	for _, p := range prims {
		switch p.Kind {
		case primLine:
			if len(p.Points) >= 4 {
				grow(p.Points[0], p.Points[1])
				grow(p.Points[2], p.Points[3])
			}
		case primPolyline:
			for i := 0; i+1 < len(p.Points); i += 2 {
				grow(p.Points[i], p.Points[i+1])
			}
		case primRect:
			grow(p.X, p.Y)
			grow(p.X+p.W, p.Y+p.H)
		case primCircle:
			grow(p.CX-p.R, p.CY-p.R)
			grow(p.CX+p.R, p.CY+p.R)
		}
	}
	return minX, minY, maxX, maxY, has
}

func normRotSteps(steps int) int {
	return ((steps % 4) + 4) % 4
}

// rotSVG90K applies k rotation steps consistent with core.LocalToWorld when mapping
// symbol-local offsets: Rotation=1 uses (-ly, lx), i.e. one step is (x,y) -> (-y,x) in SVG user units.
func rotSVG90K(x, y float64, steps int) (float64, float64) {
	s := normRotSteps(steps)
	for i := 0; i < s; i++ {
		x, y = -y, x
	}
	return x, y
}

func bboxRotatedRect(x, y, w, h float64, steps int) (float64, float64, float64, float64) {
	s := normRotSteps(steps)
	if s == 0 {
		return x, y, w, h
	}
	cx := []float64{x, x + w, x + w, x}
	cy := []float64{y, y, y + h, y + h}
	minX, maxX := cx[0], cx[0]
	minY, maxY := cy[0], cy[0]
	for i := 0; i < 4; i++ {
		rx, ry := rotSVG90K(cx[i], cy[i], s)
		if rx < minX {
			minX = rx
		}
		if rx > maxX {
			maxX = rx
		}
		if ry < minY {
			minY = ry
		}
		if ry > maxY {
			maxY = ry
		}
	}
	return minX, minY, maxX - minX, maxY - minY
}

func rotatePrimitive(p primitive, steps int) primitive {
	s := normRotSteps(steps)
	if s == 0 {
		return p
	}
	q := p
	switch p.Kind {
	case primLine:
		q.Points = make([]float64, len(p.Points))
		copy(q.Points, p.Points)
		for i := 0; i+1 < len(q.Points); i += 2 {
			q.Points[i], q.Points[i+1] = rotSVG90K(q.Points[i], q.Points[i+1], s)
		}
	case primPolyline:
		q.Points = make([]float64, len(p.Points))
		copy(q.Points, p.Points)
		for i := 0; i+1 < len(q.Points); i += 2 {
			q.Points[i], q.Points[i+1] = rotSVG90K(q.Points[i], q.Points[i+1], s)
		}
	case primRect:
		nx, ny, nw, nh := bboxRotatedRect(p.X, p.Y, p.W, p.H, s)
		q.X, q.Y, q.W, q.H = nx, ny, nw, nh
		if s%2 != 0 {
			q.Rx, q.Ry = p.Ry, p.Rx
		}
	case primCircle:
		q.CX, q.CY = rotSVG90K(p.CX, p.CY, s)
	default:
		return p
	}
	return q
}

func rotateAssetPrimitives(src svgAsset, steps int) svgAsset {
	out := svgAsset{
		ViewMinX: src.ViewMinX,
		ViewMinY: src.ViewMinY,
		ViewW:    src.ViewW,
		ViewH:    src.ViewH,
	}
	out.Prims = make([]primitive, len(src.Prims))
	for i := range src.Prims {
		out.Prims[i] = rotatePrimitive(src.Prims[i], steps)
	}
	return out
}

func rotatePinCenters(pins []svgPinCenter, steps int) []svgPinCenter {
	s := normRotSteps(steps)
	if len(pins) == 0 {
		return nil
	}
	if s == 0 {
		out := make([]svgPinCenter, len(pins))
		copy(out, pins)
		return out
	}
	out := make([]svgPinCenter, len(pins))
	for i, p := range pins {
		cx, cy := rotSVG90K(p.CX, p.CY, s)
		out[i] = svgPinCenter{CX: cx, CY: cy, ID: p.ID}
	}
	return out
}

func emitDrawPrimitives(buf *bytes.Buffer, asset svgAsset) {
	for _, prim := range asset.Prims {
		switch prim.Kind {
		case primLine:
			buf.WriteString(fmt.Sprintf(
				"\tpart.DrawVGLine(ctx, base, %.6f, %.6f, %.6f, %.6f, %.6f, %s)\n",
				prim.Points[0], prim.Points[1], prim.Points[2], prim.Points[3], prim.StrokeWidth, colorLiteral(prim.Stroke),
			))
		case primPolyline:
			buf.WriteString(fmt.Sprintf("\tpart.DrawVGPolyline(ctx, base, []float64{%s}, %t, %.6f, %s)\n",
				floatList(prim.Points), prim.Closed, prim.StrokeWidth, colorLiteral(prim.Stroke)))
		case primRect:
			if prim.Rx > 0 || prim.Ry > 0 {
				buf.WriteString(fmt.Sprintf("\tpart.DrawVGRoundedRect(ctx, base, %.6f, %.6f, %.6f, %.6f, %.6f, %.6f, %s, %t, %s, %.6f, %t)\n",
					prim.X, prim.Y, prim.W, prim.H, prim.Rx, prim.Ry,
					colorLiteral(prim.Fill), prim.HasFill, colorLiteral(prim.Stroke), prim.StrokeWidth, prim.HasStroke))
			} else {
				buf.WriteString(fmt.Sprintf("\tpart.DrawVGRect(ctx, base, %.6f, %.6f, %.6f, %.6f, %s, %t, %s, %.6f, %t)\n",
					prim.X, prim.Y, prim.W, prim.H,
					colorLiteral(prim.Fill), prim.HasFill, colorLiteral(prim.Stroke), prim.StrokeWidth, prim.HasStroke))
			}
		case primCircle:
			buf.WriteString(fmt.Sprintf("\tpart.DrawVGCircle(ctx, base, %.6f, %.6f, %.6f, %s, %t, %s, %.6f, %t)\n",
				prim.CX, prim.CY, prim.R,
				colorLiteral(prim.Fill), prim.HasFill, colorLiteral(prim.Stroke), prim.StrokeWidth, prim.HasStroke))
		}
	}
}

func loadVectorSVG(absPath string) (svgAsset, []svgPinCenter, error) {
	content, err := os.ReadFile(absPath)
	if err != nil {
		return svgAsset{}, nil, err
	}
	merged, err := parseSVG(content)
	if err != nil {
		return svgAsset{}, nil, err
	}
	validateCenteredViewBox(merged.ViewMinX, merged.ViewMinY, merged.ViewW, merged.ViewH, absPath)
	snapPinMarkersToGrid64(&merged)
	snapNearAxisStrokes(&merged)
	pins := extractRedPinMarkers(&merged)
	seenID := map[string]bool{}
	for _, p := range pins {
		if p.ID == "" {
			continue
		}
		if seenID[p.ID] {
			fail("duplicate pin marker id %q in %s", p.ID, absPath)
		}
		seenID[p.ID] = true
	}
	stripSemanticPinLabelMarkers(&merged)
	merged.Prims = orderPrimitivesFillUnderStroke(merged.Prims)
	return merged, pins, nil
}

func extractRedPinMarkers(asset *svgAsset) []svgPinCenter {
	var out []svgPinCenter
	for _, p := range asset.Prims {
		if p.Kind != primCircle || !p.HasFill {
			continue
		}
		if p.R < 0.5 {
			continue
		}
		if strings.ToUpper(strings.TrimSpace(p.Fill)) != "#FF0000" {
			continue
		}
		out = append(out, svgPinCenter{CX: p.CX, CY: p.CY, ID: p.ElemID})
	}
	return out
}

// stripSemanticPinLabelMarkers removes authoring-only circles (#FF0000 pins, #0000FF label anchor)
// from emitted draw code so they never appear on the schematic.
func stripSemanticPinLabelMarkers(asset *svgAsset) {
	dst := asset.Prims[:0]
	for _, p := range asset.Prims {
		if isSemanticPinOrLabelMarker(p) {
			continue
		}
		dst = append(dst, p)
	}
	asset.Prims = dst
}

func isSemanticPinOrLabelMarker(p primitive) bool {
	if p.Kind != primCircle {
		return false
	}
	if !p.HasFill {
		return false
	}
	switch strings.ToUpper(strings.TrimSpace(p.Fill)) {
	case "#FF0000", "#0000FF":
		return true
	default:
		return false
	}
}

// orderPrimitivesFillUnderStroke draws filled rects (e.g. capacitor plate) beneath black strokes when
// Boxy SVG lists the trace before the rect (otherwise opaque fills hide conductors).
func orderPrimitivesFillUnderStroke(prims []primitive) []primitive {
	var fillLayer, strokeLayer []primitive
	for _, p := range prims {
		if p.Kind == primRect && p.HasFill {
			fillLayer = append(fillLayer, p)
			continue
		}
		strokeLayer = append(strokeLayer, p)
	}
	out := make([]primitive, 0, len(prims))
	out = append(out, fillLayer...)
	out = append(out, strokeLayer...)
	return out
}

// svgMatrix is an SVG transform matrix(a b c d e f) row form.
type svgMatrix struct {
	a, b, c, d, e, f float64
}

func parseSVGMatrix(transform string) (svgMatrix, bool) {
	transform = strings.TrimSpace(transform)
	if transform == "" {
		return svgMatrix{}, false
	}
	if !strings.HasPrefix(strings.ToLower(strings.TrimSpace(transform)), "matrix") {
		return svgMatrix{}, false
	}
	open := strings.Index(transform, "(")
	close := strings.LastIndex(transform, ")")
	if open < 0 || close <= open {
		return svgMatrix{}, false
	}
	fields := strings.Fields(strings.ReplaceAll(transform[open+1:close], ",", " "))
	if len(fields) != 6 {
		return svgMatrix{}, false
	}
	return svgMatrix{
		a: parseFloat(fields[0], 1),
		b: parseFloat(fields[1], 0),
		c: parseFloat(fields[2], 0),
		d: parseFloat(fields[3], 1),
		e: parseFloat(fields[4], 0),
		f: parseFloat(fields[5], 0),
	}, true
}

func transformSVGMatrix(m svgMatrix, x, y float64) (float64, float64) {
	xp := m.a*x + m.c*y + m.e
	yp := m.b*x + m.d*y + m.f
	return xp, yp
}

const pinGridSnap = 64.0

// Near-axis snapping (SVG user units): nearly horizontal/vertical strokes align to axis so
// rasterization does not staircase when Boxy leaves small coordinate drift.
const (
	axisSnapEpsAbs   = 1.5   // max perpendicular deviation allowed
	axisSnapEpsRel   = 0.02  // scaled by segment length
	axisSnapSlopeMax = 0.035 // max |Δ⊥|/|Δalong| (~2°); avoids flattening long shallow diagonals
)

func snapLineSegmentEndpoints(x1, y1, x2, y2 float64) (float64, float64, float64, float64) {
	dx := x2 - x1
	dy := y2 - y1
	length := math.Hypot(dx, dy)
	if length < 1e-9 {
		return x1, y1, x2, y2
	}
	thr := math.Max(axisSnapEpsAbs, axisSnapEpsRel*length)
	capH := math.Min(thr, math.Abs(dx)*axisSnapSlopeMax)
	capV := math.Min(thr, math.Abs(dy)*axisSnapSlopeMax)
	horiz := math.Abs(dy) <= capH && math.Abs(dx) > 1e-12
	vert := math.Abs(dx) <= capV && math.Abs(dy) > 1e-12
	switch {
	case horiz && vert:
		if math.Abs(dx) >= math.Abs(dy) {
			y := (y1 + y2) * 0.5
			return x1, y, x2, y
		}
		x := (x1 + x2) * 0.5
		return x, y1, x, y2
	case horiz:
		y := (y1 + y2) * 0.5
		return x1, y, x2, y
	case vert:
		x := (x1 + x2) * 0.5
		return x, y1, x, y2
	default:
		return x1, y1, x2, y2
	}
}

func snapPolylinePoints(points []float64, closed bool) []float64 {
	n := len(points) / 2
	if n < 2 {
		return points
	}
	type seg struct {
		i, j int
	}
	var segs []seg
	for k := 0; k < n-1; k++ {
		segs = append(segs, seg{k, k + 1})
	}
	if closed && n >= 3 {
		segs = append(segs, seg{n - 1, 0})
	}
	xs := make([]float64, n)
	ys := make([]float64, n)
	counts := make([]int, n)
	for _, s := range segs {
		x1, y1 := points[s.i*2], points[s.i*2+1]
		x2, y2 := points[s.j*2], points[s.j*2+1]
		sx1, sy1, sx2, sy2 := snapLineSegmentEndpoints(x1, y1, x2, y2)
		xs[s.i] += sx1
		ys[s.i] += sy1
		counts[s.i]++
		xs[s.j] += sx2
		ys[s.j] += sy2
		counts[s.j]++
	}
	out := make([]float64, len(points))
	for i := 0; i < n; i++ {
		if counts[i] == 0 {
			out[i*2] = points[i*2]
			out[i*2+1] = points[i*2+1]
			continue
		}
		out[i*2] = xs[i] / float64(counts[i])
		out[i*2+1] = ys[i] / float64(counts[i])
	}
	return out
}

func snapNearAxisStrokes(asset *svgAsset) {
	for i := range asset.Prims {
		switch asset.Prims[i].Kind {
		case primLine:
			p := asset.Prims[i].Points
			if len(p) >= 4 {
				x1, y1, x2, y2 := snapLineSegmentEndpoints(p[0], p[1], p[2], p[3])
				p[0], p[1], p[2], p[3] = x1, y1, x2, y2
			}
		case primPolyline:
			asset.Prims[i].Points = snapPolylinePoints(asset.Prims[i].Points, asset.Prims[i].Closed)
		}
	}
}

// snapPinMarkersToGrid64 moves red pin-marker circle centers to the nearest
// intersection of the 64 user-unit grid (same grid as authoring; viewBox 512 → 9 columns).
func snapPinMarkersToGrid64(asset *svgAsset) {
	for i := range asset.Prims {
		if asset.Prims[i].Kind != primCircle {
			continue
		}
		if !asset.Prims[i].HasFill {
			continue
		}
		if strings.ToUpper(strings.TrimSpace(asset.Prims[i].Fill)) != "#FF0000" {
			continue
		}
		asset.Prims[i].CX = math.Round(asset.Prims[i].CX/pinGridSnap) * pinGridSnap
		asset.Prims[i].CY = math.Round(asset.Prims[i].CY/pinGridSnap) * pinGridSnap
	}
}

// rejectUnhandledTransform fails fast on transform attributes the generator does not bake into primitives.
// Circles and ellipses may use transform="matrix(...)" only (applied to center); everything else must be
// baked in Boxy (Object → Transform → Bake Transform) before running this tool.
func rejectUnhandledTransform(elemLocal string, attr map[string]string) error {
	tr := strings.TrimSpace(attr["transform"])
	if tr == "" {
		return nil
	}
	switch elemLocal {
	case "circle", "ellipse":
		if _, ok := parseSVGMatrix(tr); ok {
			return nil
		}
		return fmt.Errorf("<%s>: unsupported transform %q — use matrix(...) or bake with Boxy SVG (Object → Transform → Bake Transform)", elemLocal, tr)
	default:
		return fmt.Errorf("<%s>: transform not supported by gen_part_vectors — bake in Boxy SVG so geometry has no transform attribute (got %q)", elemLocal, tr)
	}
}

func parseSVG(data []byte) (svgAsset, error) {
	dec := xml.NewDecoder(bytes.NewReader(data))
	var out svgAsset
	for {
		tok, err := dec.Token()
		if err != nil {
			if err.Error() == "EOF" {
				break
			}
			return svgAsset{}, err
		}
		start, ok := tok.(xml.StartElement)
		if !ok {
			continue
		}
		attr := mergePresentation(attrs(start.Attr))
		switch start.Name.Local {
		case "svg":
			if tr := strings.TrimSpace(attr["transform"]); tr != "" {
				return svgAsset{}, fmt.Errorf("<svg>: root transform not supported — bake or remove before codegen (got %q)", tr)
			}
			vb := strings.Fields(attr["viewBox"])
			if len(vb) == 4 {
				out.ViewMinX = parseFloat(vb[0], 0)
				out.ViewMinY = parseFloat(vb[1], 0)
				out.ViewW = parseFloat(vb[2], 1)
				out.ViewH = parseFloat(vb[3], 1)
			}
		case "g":
			if err := rejectUnhandledTransform("g", attr); err != nil {
				return svgAsset{}, err
			}
		case "line":
			if err := rejectUnhandledTransform("line", attr); err != nil {
				return svgAsset{}, err
			}
			stroke := attr["stroke"]
			p := primitive{
				Kind:        primLine,
				Points:      []float64{parseFloat(attr["x1"], 0), parseFloat(attr["y1"], 0), parseFloat(attr["x2"], 0), parseFloat(attr["y2"], 0)},
				StrokeWidth: parseFloat(attr["stroke-width"], 1),
				Stroke:      canonStroke(stroke),
				HasStroke:   hasPaint(stroke),
			}
			if p.HasStroke {
				out.Prims = append(out.Prims, p)
			}
		case "polyline", "polygon":
			if err := rejectUnhandledTransform(start.Name.Local, attr); err != nil {
				return svgAsset{}, err
			}
			stroke := attr["stroke"]
			points := parsePoints(attr["points"])
			p := primitive{
				Kind:        primPolyline,
				Points:      points,
				Closed:      start.Name.Local == "polygon",
				StrokeWidth: parseFloat(attr["stroke-width"], 1),
				Stroke:      canonStroke(stroke),
				HasStroke:   hasPaint(stroke),
			}
			if p.HasStroke && len(points) >= 4 {
				out.Prims = append(out.Prims, p)
			}
		case "rect":
			if err := rejectUnhandledTransform("rect", attr); err != nil {
				return svgAsset{}, err
			}
			fill := attr["fill"]
			stroke := attr["stroke"]
			rx := parseFloat(attr["rx"], 0)
			ry := parseFloat(attr["ry"], 0)
			if ry == 0 && rx > 0 {
				ry = rx
			}
			if rx == 0 && ry > 0 {
				rx = ry
			}
			p := primitive{
				Kind:        primRect,
				X:           parseFloat(attr["x"], 0),
				Y:           parseFloat(attr["y"], 0),
				W:           parseFloat(attr["width"], 0),
				H:           parseFloat(attr["height"], 0),
				Rx:          rx,
				Ry:          ry,
				Fill:        canonFill(fill),
				HasFill:     hasPaint(fill) && attr["clip-path"] == "",
				Stroke:      canonStroke(stroke),
				HasStroke:   hasPaint(stroke),
				StrokeWidth: parseFloat(attr["stroke-width"], 1),
			}
			if p.HasFill || p.HasStroke {
				out.Prims = append(out.Prims, p)
			}
		case "circle":
			if err := rejectUnhandledTransform("circle", attr); err != nil {
				return svgAsset{}, err
			}
			fill := attr["fill"]
			stroke := attr["stroke"]
			p := primitive{
				Kind:        primCircle,
				CX:          parseFloat(attr["cx"], 0),
				CY:          parseFloat(attr["cy"], 0),
				R:           parseFloat(attr["r"], 0),
				Fill:        canonFill(fill),
				HasFill:     hasPaint(fill),
				Stroke:      canonStroke(stroke),
				HasStroke:   hasPaint(stroke),
				StrokeWidth: parseFloat(attr["stroke-width"], 1),
				ElemID:      strings.TrimSpace(attr["id"]),
			}
			if mat, ok := parseSVGMatrix(attr["transform"]); ok {
				p.CX, p.CY = transformSVGMatrix(mat, p.CX, p.CY)
			}
			if p.HasFill || p.HasStroke {
				out.Prims = append(out.Prims, p)
			}
		case "ellipse":
			if err := rejectUnhandledTransform("ellipse", attr); err != nil {
				return svgAsset{}, err
			}
			rx := parseFloat(attr["rx"], 0)
			ry := parseFloat(attr["ry"], 0)
			r := rx
			if ry > r {
				r = ry
			}
			fill := attr["fill"]
			stroke := attr["stroke"]
			p := primitive{
				Kind:        primCircle,
				CX:          parseFloat(attr["cx"], 0),
				CY:          parseFloat(attr["cy"], 0),
				R:           r,
				Fill:        canonFill(fill),
				HasFill:     hasPaint(fill),
				Stroke:      canonStroke(stroke),
				HasStroke:   hasPaint(stroke),
				StrokeWidth: parseFloat(attr["stroke-width"], 1),
				ElemID:      strings.TrimSpace(attr["id"]),
			}
			if mat, ok := parseSVGMatrix(attr["transform"]); ok {
				p.CX, p.CY = transformSVGMatrix(mat, p.CX, p.CY)
			}
			if p.HasFill || p.HasStroke {
				out.Prims = append(out.Prims, p)
			}
		case "path":
			stroke := attr["stroke"]
			if !hasPaint(stroke) {
				continue
			}
			tr := strings.TrimSpace(attr["transform"])
			var pathMat svgMatrix
			pathHasMat := false
			if tr != "" {
				var ok bool
				pathMat, ok = parseSVGMatrix(tr)
				if !ok {
					return svgAsset{}, fmt.Errorf("<path>: transform must be matrix(...) or bake in Boxy — unsupported %q", tr)
				}
				pathHasMat = true
			}
			strokeWidth := parseFloat(attr["stroke-width"], 1)
			polylines, err := pathToPolylines(attr["d"])
			if err != nil {
				return svgAsset{}, err
			}
			for _, points := range polylines {
				if len(points) < 4 {
					continue
				}
				if pathHasMat {
					for i := 0; i < len(points); i += 2 {
						points[i], points[i+1] = transformSVGMatrix(pathMat, points[i], points[i+1])
					}
				}
				out.Prims = append(out.Prims, primitive{
					Kind:        primPolyline,
					Points:      points,
					StrokeWidth: strokeWidth,
					Stroke:      canonStroke(stroke),
					HasStroke:   true,
				})
			}
		}
	}
	if out.ViewW <= 0 || out.ViewH <= 0 {
		return svgAsset{}, fmt.Errorf("missing viewBox")
	}
	return out, nil
}

func pathToPolylines(d string) ([][]float64, error) {
	tokens := tokenizePath(d)
	var out [][]float64
	var curX, curY float64
	var startX, startY float64
	var i int
	for i < len(tokens) {
		cmd := tokens[i]
		i++
		switch cmd {
		case "M":
			if i+1 >= len(tokens) {
				return nil, fmt.Errorf("invalid M")
			}
			curX = parseFloat(tokens[i], 0)
			curY = parseFloat(tokens[i+1], 0)
			startX, startY = curX, curY
			i += 2
		case "L":
			if i+1 >= len(tokens) {
				return nil, fmt.Errorf("invalid L")
			}
			x := parseFloat(tokens[i], 0)
			y := parseFloat(tokens[i+1], 0)
			out = append(out, []float64{curX, curY, x, y})
			curX, curY = x, y
			i += 2
		case "A":
			if i+6 >= len(tokens) {
				return nil, fmt.Errorf("invalid A")
			}
			rx := parseFloat(tokens[i], 0)
			ry := parseFloat(tokens[i+1], 0)
			largeArc := parseFloat(tokens[i+3], 0) != 0
			sweep := parseFloat(tokens[i+4], 0) != 0
			x := parseFloat(tokens[i+5], 0)
			y := parseFloat(tokens[i+6], 0)
			pts := approximateArc(curX, curY, x, y, rx, ry, largeArc, sweep)
			if len(pts) >= 4 {
				out = append(out, pts)
			}
			curX, curY = x, y
			i += 7
		case "C":
			if i+5 >= len(tokens) {
				return nil, fmt.Errorf("invalid C")
			}
			cx1 := parseFloat(tokens[i], 0)
			cy1 := parseFloat(tokens[i+1], 0)
			cx2 := parseFloat(tokens[i+2], 0)
			cy2 := parseFloat(tokens[i+3], 0)
			x := parseFloat(tokens[i+4], 0)
			y := parseFloat(tokens[i+5], 0)
			flat := flattenCubicBezier(curX, curY, cx1, cy1, cx2, cy2, x, y, 24)
			for k := 0; k+3 < len(flat); k += 2 {
				out = append(out, []float64{flat[k], flat[k+1], flat[k+2], flat[k+3]})
			}
			curX, curY = x, y
			i += 6
		case "Z":
			out = append(out, []float64{curX, curY, startX, startY})
			curX, curY = startX, startY
		default:
			return nil, fmt.Errorf("unsupported path cmd: %s", cmd)
		}
	}
	return out, nil
}

func flattenCubicBezier(x0, y0, x1, y1, x2, y2, x3, y3 float64, segments int) []float64 {
	if segments < 2 {
		segments = 2
	}
	out := make([]float64, 0, (segments+1)*2)
	for i := 0; i <= segments; i++ {
		t := float64(i) / float64(segments)
		out = append(out,
			cubicBezier(x0, x1, x2, x3, t),
			cubicBezier(y0, y1, y2, y3, t),
		)
	}
	return out
}

func cubicBezier(p0, p1, p2, p3, t float64) float64 {
	u := 1 - t
	return u*u*u*p0 + 3*u*u*t*p1 + 3*u*t*t*p2 + t*t*t*p3
}

func approximateArc(x1, y1, x2, y2, rx, ry float64, largeArc, sweep bool) []float64 {
	if rx == 0 || ry == 0 {
		return []float64{x1, y1, x2, y2}
	}
	dx := (x1 - x2) / 2
	dy := (y1 - y2) / 2
	rx2 := rx * rx
	ry2 := ry * ry
	xp2 := dx * dx
	yp2 := dy * dy
	lambda := xp2/rx2 + yp2/ry2
	if lambda > 1 {
		scale := mathSqrt(lambda)
		rx *= scale
		ry *= scale
		rx2 = rx * rx
		ry2 = ry * ry
	}
	num := rx2*ry2 - rx2*yp2 - ry2*xp2
	den := rx2*yp2 + ry2*xp2
	if den == 0 {
		return []float64{x1, y1, x2, y2}
	}
	f := mathSqrt(max0(num / den))
	if largeArc == sweep {
		f = -f
	}
	cxp := f * (rx * dy / ry)
	cyp := f * (-ry * dx / rx)
	cx := (x1+x2)/2 + cxp
	cy := (y1+y2)/2 + cyp
	theta1 := mathAtan2((dy-cyp)/ry, (dx-cxp)/rx)
	theta2 := mathAtan2((-dy-cyp)/ry, (-dx-cxp)/rx)
	delta := theta2 - theta1
	if !sweep && delta > 0 {
		delta -= 2 * mathPi
	}
	if sweep && delta < 0 {
		delta += 2 * mathPi
	}
	steps := int(mathCeil(mathAbs(delta) / (mathPi / 10)))
	if steps < 2 {
		steps = 2
	}
	pts := make([]float64, 0, (steps+1)*2)
	for i := 0; i <= steps; i++ {
		t := theta1 + (delta*float64(i))/float64(steps)
		x := cx + rx*mathCos(t)
		y := cy + ry*mathSin(t)
		pts = append(pts, x, y)
	}
	return pts
}

func tokenizePath(d string) []string {
	repl := strings.NewReplacer(",", " ", "\n", " ", "\t", " ")
	s := repl.Replace(d)
	var out []string
	var cur strings.Builder
	flush := func() {
		if cur.Len() > 0 {
			out = append(out, cur.String())
			cur.Reset()
		}
	}
	for _, r := range s {
		if strings.ContainsRune("MLCAZ", r) {
			flush()
			out = append(out, string(r))
			continue
		}
		if r == ' ' {
			flush()
			continue
		}
		cur.WriteRune(r)
	}
	flush()
	return out
}

func parsePoints(s string) []float64 {
	repl := strings.NewReplacer(",", " ", "\n", " ", "\t", " ")
	fields := strings.Fields(repl.Replace(s))
	points := make([]float64, 0, len(fields))
	for _, f := range fields {
		points = append(points, parseFloat(f, 0))
	}
	return points
}

// mergePresentation overlays CSS from the style attribute on top of XML attributes.
// Tools such as Boxy SVG often emit only style="fill: rgb(...); stroke: ...".
func mergePresentation(attr map[string]string) map[string]string {
	out := make(map[string]string, len(attr)+8)
	for k, v := range attr {
		out[k] = v
	}
	st := strings.TrimSpace(attr["style"])
	if st == "" {
		return out
	}
	for k, v := range parseInlineStyle(st) {
		out[k] = v
	}
	return out
}

func parseInlineStyle(style string) map[string]string {
	out := make(map[string]string)
	for _, piece := range strings.Split(style, ";") {
		piece = strings.TrimSpace(piece)
		if piece == "" {
			continue
		}
		idx := strings.IndexByte(piece, ':')
		if idx <= 0 {
			continue
		}
		k := strings.TrimSpace(strings.ToLower(piece[:idx]))
		v := strings.TrimSpace(piece[idx+1:])
		out[k] = v
	}
	return out
}

func canonStroke(s string) string {
	if !hasPaint(s) {
		return "#000000"
	}
	return normalizePaintToHex(s)
}

func canonFill(s string) string {
	if !hasPaint(s) {
		return "#000000"
	}
	return normalizePaintToHex(s)
}

// normalizePaintToHex converts SVG/CSS paint strings to canonical "#RRGGBB" or "#RRGGBBAA"
// so codegen preserves authored colors (not only black / white / red pin markers).
func normalizePaintToHex(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "#000000"
	}
	low := strings.ToLower(s)

	switch low {
	case "transparent":
		return "#00000000"
	case "currentcolor":
		return "#000000"
	}

	if strings.HasPrefix(s, "#") {
		switch len(s) {
		case 7:
			return strings.ToUpper(s)
		case 9:
			return strings.ToUpper(s)
		case 4:
			return strings.ToUpper(fmt.Sprintf("#%c%c%c%c%c%c", s[1], s[1], s[2], s[2], s[3], s[3]))
		}
	}

	if strings.HasPrefix(low, "rgb(") || strings.HasPrefix(low, "rgba(") {
		if hex, ok := functionalRGBToHex(s); ok {
			return hex
		}
	}

	if c, ok := colornames.Map[low]; ok {
		return fmt.Sprintf("#%02X%02X%02X", c.R, c.G, c.B)
	}

	if strings.HasPrefix(s, "#") && len(s) > 1 {
		digits := strings.TrimPrefix(s, "#")
		if len(digits) == 6 || len(digits) == 8 {
			for _, ch := range digits {
				isHex := (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') || (ch >= 'A' && ch <= 'F')
				if !isHex {
					return "#000000"
				}
			}
			return strings.ToUpper("#" + digits)
		}
	}

	return "#000000"
}

func functionalRGBToHex(s string) (string, bool) {
	s = strings.TrimSpace(s)
	low := strings.ToLower(s)
	var isRGBA bool
	switch {
	case strings.HasPrefix(low, "rgba("):
		isRGBA = true
	case strings.HasPrefix(low, "rgb("):
		isRGBA = false
	default:
		return "", false
	}
	open := strings.IndexByte(s, '(')
	close := strings.LastIndexByte(s, ')')
	if open < 0 || close <= open {
		return "", false
	}
	inner := strings.TrimSpace(s[open+1 : close])
	a := byte(255)
	slash := strings.Contains(inner, "/")
	var rgbFields []string
	if slash {
		idx := strings.Index(inner, "/")
		a = parseAlphaToken(strings.TrimSpace(inner[idx+1:]))
		rgbFields = splitCommaOrSpaceTokens(strings.TrimSpace(inner[:idx]))
	} else if isRGBA {
		rgbFields = splitCommaOrSpaceTokens(inner)
		if len(rgbFields) != 4 {
			return "", false
		}
		a = parseAlphaToken(rgbFields[3])
		rgbFields = rgbFields[:3]
	} else {
		rgbFields = splitCommaOrSpaceTokens(inner)
		if len(rgbFields) != 3 {
			return "", false
		}
	}
	if len(rgbFields) != 3 {
		return "", false
	}
	r := parseChannelToken(rgbFields[0])
	g := parseChannelToken(rgbFields[1])
	b := parseChannelToken(rgbFields[2])
	out := fmt.Sprintf("#%02X%02X%02X", r, g, b)
	if a != 255 {
		out += fmt.Sprintf("%02X", a)
	}
	return out, true
}

func splitCommaOrSpaceTokens(inner string) []string {
	var out []string
	for _, seg := range strings.Split(inner, ",") {
		for _, t := range strings.Fields(seg) {
			out = append(out, t)
		}
	}
	return out
}

func parseChannelToken(tok string) byte {
	tok = strings.TrimSpace(tok)
	if strings.HasSuffix(tok, "%") {
		v := parseFloat(strings.TrimSuffix(tok, "%"), 0)
		return clampByte(math.Round(v * 255 / 100))
	}
	v := parseFloat(tok, 0)
	return clampByte(math.Round(v))
}

func parseAlphaToken(tok string) byte {
	tok = strings.TrimSpace(tok)
	if strings.HasSuffix(tok, "%") {
		v := parseFloat(strings.TrimSuffix(tok, "%"), 100)
		return clampByte(math.Round(v * 255 / 100))
	}
	v := parseFloat(tok, 1)
	if v <= 1 {
		return clampByte(math.Round(v * 255))
	}
	return clampByte(math.Round(v))
}

func clampByte(v float64) byte {
	if v < 0 {
		return 0
	}
	if v > 255 {
		return 255
	}
	return byte(v)
}

func attrs(in []xml.Attr) map[string]string {
	// Boxy SVG duplicates path data as bx:d (same Local name "d"); prefer standard unprefixed d.
	out := make(map[string]string, len(in))
	var pathD, pathDBX string
	for _, a := range in {
		if a.Name.Local == "d" {
			if a.Name.Space == "" {
				pathD = a.Value
			} else {
				pathDBX = a.Value
			}
			continue
		}
		out[a.Name.Local] = a.Value
	}
	switch {
	case pathD != "":
		out["d"] = pathD
	case pathDBX != "":
		out["d"] = pathDBX
	}
	return out
}

func parseFloat(s string, fallback float64) float64 {
	s = strings.TrimSpace(strings.TrimSuffix(strings.TrimSuffix(s, "px"), "%"))
	if s == "" {
		return fallback
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return fallback
	}
	return v
}

func hasPaint(v string) bool {
	v = strings.TrimSpace(strings.ToLower(v))
	return v != "" && v != "none"
}

func colorOrDefault(v, fallback string) string {
	if !hasPaint(v) {
		return fallback
	}
	return v
}

func colorLiteral(hex string) string {
	hex = strings.TrimPrefix(strings.TrimSpace(hex), "#")
	switch len(hex) {
	case 6:
		r := parseHex(hex[0:2])
		g := parseHex(hex[2:4])
		b := parseHex(hex[4:6])
		return fmt.Sprintf("color.RGBA{R:%d, G:%d, B:%d, A:255}", r, g, b)
	case 8:
		r := parseHex(hex[0:2])
		g := parseHex(hex[2:4])
		b := parseHex(hex[4:6])
		a := parseHex(hex[6:8])
		return fmt.Sprintf("color.RGBA{R:%d, G:%d, B:%d, A:%d}", r, g, b, a)
	default:
		return "color.RGBA{R:0, G:0, B:0, A:255}"
	}
}

func parseHex(s string) int64 {
	v, err := strconv.ParseInt(s, 16, 64)
	if err != nil {
		return 0
	}
	return v
}

func floatList(v []float64) string {
	out := make([]string, 0, len(v))
	for _, n := range v {
		out = append(out, fmt.Sprintf("%.6f", n))
	}
	return strings.Join(out, ", ")
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

func max0(v float64) float64 {
	if v < 0 {
		return 0
	}
	return v
}

const mathPi = math.Pi

func mathSqrt(v float64) float64 { return math.Sqrt(v) }
func mathCos(v float64) float64  { return math.Cos(v) }
func mathSin(v float64) float64  { return math.Sin(v) }
func mathAtan2(y, x float64) float64 {
	return math.Atan2(y, x)
}
func mathAbs(v float64) float64  { return math.Abs(v) }
func mathCeil(v float64) float64 { return math.Ceil(v) }
