// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Pin fields match red authoring circle id attributes in catalog SVGs (see vectors_gen.go RegisterPinLayout).

package indicator

import "coilforge/internal/core"

// IndicatorPinIDs holds stable pin identity for this catalog type.
type IndicatorPinIDs struct {
	TerminalA core.PinID `json:"terminalA"`
	TerminalB core.PinID `json:"terminalB"`
}

// indicatorPinMarkerMap maps SVG marker ids from the vector layout to pin IDs for anchor placement.
func indicatorPinMarkerMap(self *Indicator) map[string]core.PinID {
	return map[string]core.PinID{
		"TerminalA": self.TerminalA,
		"TerminalB": self.TerminalB,
	}
}

// assignNewIndicatorPins allocates fresh pin IDs (e.g. clone).
func assignNewIndicatorPins(self *Indicator, alloc func() core.PinID) {
	self.TerminalA = alloc()
	self.TerminalB = alloc()
}
