// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Vector names are <stem>-<0..n> from schematic SVGs (underscores → hyphens), excluding toolbar btn_*.svg.
// Without _45: indices 0..3 are quarter-turn steps of the canonical SVG.
// With *-stem_45.svg: indices 0..7 interleave canonical and diagonal art (even idx = canonical, odd = _45); idx/2 is the quarter-turn on that source.
// Each suffix bakes k BasePart.Rotation steps in SVG user space (same convention as core.LocalToWorld); catalog draw passes identity rotation.
package indicator

import (
	"coilforge/internal/core"
	"coilforge/internal/part"
	"image/color"
)

const RotationSlots = 8

func init() {
	part.RegisterVectorDraw("indicator-off-0", drawVector_indicator_off_0)
	part.RegisterPinLayout("indicator-off-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:0.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-off-0", -134.098000, -63.158000, 134.098000, 63.158000)
	part.RegisterVectorDraw("indicator-off-1", drawVector_indicator_off_1)
	part.RegisterPinLayout("indicator-off-1", []core.Pt{
		{X:-128.000000, Y:128.000000},
		{X:128.000000, Y:-128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-off-1", -128.000000, -128.839996, 128.840996, 128.000000)
	part.RegisterVectorDraw("indicator-off-2", drawVector_indicator_off_2)
	part.RegisterPinLayout("indicator-off-2", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:-0.000000, Y:128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-off-2", -63.158000, -134.098000, 63.158000, 134.098000)
	part.RegisterVectorDraw("indicator-off-3", drawVector_indicator_off_3)
	part.RegisterPinLayout("indicator-off-3", []core.Pt{
		{X:-128.000000, Y:-128.000000},
		{X:128.000000, Y:128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-off-3", -128.000000, -128.000000, 128.839996, 128.840996)
	part.RegisterVectorDraw("indicator-off-4", drawVector_indicator_off_4)
	part.RegisterPinLayout("indicator-off-4", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:-0.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-off-4", -134.098000, -63.158000, 134.098000, 63.158000)
	part.RegisterVectorDraw("indicator-off-5", drawVector_indicator_off_5)
	part.RegisterPinLayout("indicator-off-5", []core.Pt{
		{X:128.000000, Y:-128.000000},
		{X:-128.000000, Y:128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-off-5", -128.840996, -128.000000, 128.000000, 128.839996)
	part.RegisterVectorDraw("indicator-off-6", drawVector_indicator_off_6)
	part.RegisterPinLayout("indicator-off-6", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:0.000000, Y:-128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-off-6", -63.158000, -134.098000, 63.158000, 134.098000)
	part.RegisterVectorDraw("indicator-off-7", drawVector_indicator_off_7)
	part.RegisterPinLayout("indicator-off-7", []core.Pt{
		{X:128.000000, Y:128.000000},
		{X:-128.000000, Y:-128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-off-7", -128.839996, -128.840996, 128.000000, 128.000000)
	part.RegisterVectorDraw("indicator-on-0", drawVector_indicator_on_0)
	part.RegisterPinLayout("indicator-on-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:0.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-on-0", -128.000000, -63.158000, 128.000000, 63.158000)
	part.RegisterVectorDraw("indicator-on-1", drawVector_indicator_on_1)
	part.RegisterPinLayout("indicator-on-1", []core.Pt{
		{X:-128.000000, Y:128.000000},
		{X:128.000000, Y:-128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-on-1", -128.000000, -128.839996, 128.840996, 128.000000)
	part.RegisterVectorDraw("indicator-on-2", drawVector_indicator_on_2)
	part.RegisterPinLayout("indicator-on-2", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:-0.000000, Y:128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-on-2", -63.158000, -128.000000, 63.158000, 128.000000)
	part.RegisterVectorDraw("indicator-on-3", drawVector_indicator_on_3)
	part.RegisterPinLayout("indicator-on-3", []core.Pt{
		{X:-128.000000, Y:-128.000000},
		{X:128.000000, Y:128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-on-3", -128.000000, -128.000000, 128.839996, 128.840996)
	part.RegisterVectorDraw("indicator-on-4", drawVector_indicator_on_4)
	part.RegisterPinLayout("indicator-on-4", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:-0.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-on-4", -128.000000, -63.158000, 128.000000, 63.158000)
	part.RegisterVectorDraw("indicator-on-5", drawVector_indicator_on_5)
	part.RegisterPinLayout("indicator-on-5", []core.Pt{
		{X:128.000000, Y:-128.000000},
		{X:-128.000000, Y:128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-on-5", -128.840996, -128.000000, 128.000000, 128.839996)
	part.RegisterVectorDraw("indicator-on-6", drawVector_indicator_on_6)
	part.RegisterPinLayout("indicator-on-6", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:0.000000, Y:-128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-on-6", -63.158000, -128.000000, 63.158000, 128.000000)
	part.RegisterVectorDraw("indicator-on-7", drawVector_indicator_on_7)
	part.RegisterPinLayout("indicator-on-7", []core.Pt{
		{X:128.000000, Y:128.000000},
		{X:-128.000000, Y:-128.000000},
	}, []string{
		"TerminalA",
		"TerminalB",
	})
	part.RegisterVectorHitBounds("indicator-on-7", -128.839996, -128.840996, 128.000000, 128.000000)
}

func drawVector_indicator_off_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000000, 0.000000, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-62.940000, 0.000000, -134.098000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{62.940000, 0.000000, 134.098000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.536277, -45.001704, -45.351015, 45.527791}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.254848, -45.254848, 45.274647, 45.632443}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000007, 0.000003, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{64.020059, 0.251024, -64.260465, 0.251024}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-0.141421, -64.266837, -0.141421, 64.013687}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.840996, -128.839996, 45.340996, -45.365996}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-44.500000, 44.527000, -128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000000, 0.000000, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-0.000000, -62.940000, -0.000000, -134.098000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-0.000000, 62.940000, -0.000000, 134.098000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.001704, 45.536277, -45.527791, -45.351015}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.254848, -45.254848, -45.632443, 45.274647}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000003, 0.000007, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-0.251024, 64.020059, -0.251024, -64.260465}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.266837, -0.141421, -64.013687, -0.141421}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.839996, 128.840996, 45.365996, 45.340996}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-44.527000, -44.500000, -128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_4(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000000, -0.000000, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{62.940000, -0.000000, 134.098000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-62.940000, -0.000000, -134.098000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.536277, 45.001704, 45.351015, -45.527791}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.254848, 45.254848, -45.274647, -45.632443}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_5(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000007, -0.000003, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-64.020059, -0.251024, 64.260465, -0.251024}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{0.141421, 64.266837, 0.141421, -64.013687}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.840996, 128.839996, -45.340996, 45.365996}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{44.500000, -44.527000, 128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_6(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000000, -0.000000, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{0.000000, 62.940000, 0.000000, 134.098000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{0.000000, -62.940000, 0.000000, -134.098000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.001704, -45.536277, 45.527791, 45.351015}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.254848, 45.254848, 45.632443, -45.274647}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_7(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000003, -0.000007, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{0.251024, -64.020059, 0.251024, 64.260465}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.266837, 0.141421, 64.013687, 0.141421}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.839996, -128.840996, -45.365996, -45.340996}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{44.527000, 44.500000, 128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000000, 0.000000, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, 0.000000, -128.000000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.000000, 0.000000, 128.000000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.695000, -45.144000, -45.192000, 45.385000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.391000, -45.303000, 45.138000, 45.584000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000007, 0.000003, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{64.020059, 0.251024, -64.260465, 0.251024}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-0.141421, -64.266837, -0.141421, 64.013687}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.840996, -128.839996, 45.340996, -45.365996}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-44.500000, 44.527000, -128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000000, 0.000000, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-0.000000, -64.000000, -0.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-0.000000, 64.000000, -0.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.144000, 45.695000, -45.385000, -45.192000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.303000, -45.391000, -45.584000, 45.138000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000003, 0.000007, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-0.251024, 64.020059, -0.251024, -64.260465}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.266837, -0.141421, -64.013687, -0.141421}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{128.839996, 128.840996, 45.365996, 45.340996}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-44.527000, -44.500000, -128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_4(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000000, -0.000000, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{64.000000, -0.000000, 128.000000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, -0.000000, -128.000000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.695000, 45.144000, 45.192000, -45.385000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.391000, 45.303000, -45.138000, -45.584000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_5(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000007, -0.000003, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-64.020059, -0.251024, 64.260465, -0.251024}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{0.141421, 64.266837, 0.141421, -64.013687}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.840996, 128.839996, -45.340996, 45.365996}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{44.500000, -44.527000, 128.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_6(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000000, -0.000000, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{0.000000, 64.000000, 0.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{0.000000, -64.000000, 0.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.144000, -45.695000, 45.385000, 45.192000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.303000, 45.391000, 45.584000, -45.138000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_7(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000003, -0.000007, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{0.251024, -64.020059, 0.251024, 64.260465}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.266837, 0.141421, 64.013687, 0.141421}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-128.839996, -128.840996, -45.365996, -45.340996}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{44.527000, 44.500000, 128.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

