// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Vector names are <stem>-<0..3> with stem from schematic SVG filenames (underscores → hyphens), excluding toolbar btn_*.svg.
// Each suffix bakes k BasePart.Rotation steps in SVG user space (same convention as core.LocalToWorld); catalog draw passes identity rotation.
package indicator

import (
	"coilforge/internal/core"
	"coilforge/internal/part"
	"image/color"
)

func init() {
	part.RegisterVectorDraw("indicator-off-0", drawVector_indicator_off_0)
	part.RegisterPinLayout("indicator-off-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:0.000000},
	}, []string{
		"PinA",
		"PinB",
	})
	part.RegisterVectorHitBounds("indicator-off-0", -134.098000, -63.158000, 134.098000, 63.158000)
	part.RegisterVectorDraw("indicator-off-1", drawVector_indicator_off_1)
	part.RegisterPinLayout("indicator-off-1", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:-0.000000, Y:128.000000},
	}, []string{
		"PinA",
		"PinB",
	})
	part.RegisterVectorHitBounds("indicator-off-1", -63.158000, -134.098000, 63.158000, 134.098000)
	part.RegisterVectorDraw("indicator-off-2", drawVector_indicator_off_2)
	part.RegisterPinLayout("indicator-off-2", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:-0.000000},
	}, []string{
		"PinA",
		"PinB",
	})
	part.RegisterVectorHitBounds("indicator-off-2", -134.098000, -63.158000, 134.098000, 63.158000)
	part.RegisterVectorDraw("indicator-off-3", drawVector_indicator_off_3)
	part.RegisterPinLayout("indicator-off-3", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:0.000000, Y:-128.000000},
	}, []string{
		"PinA",
		"PinB",
	})
	part.RegisterVectorHitBounds("indicator-off-3", -63.158000, -134.098000, 63.158000, 134.098000)
	part.RegisterVectorDraw("indicator-on-0", drawVector_indicator_on_0)
	part.RegisterPinLayout("indicator-on-0", []core.Pt{
		{X:-128.000000, Y:0.000000},
		{X:128.000000, Y:0.000000},
	}, []string{
		"PinA",
		"PinB",
	})
	part.RegisterVectorHitBounds("indicator-on-0", -128.000000, -63.158000, 128.000000, 63.158000)
	part.RegisterVectorDraw("indicator-on-1", drawVector_indicator_on_1)
	part.RegisterPinLayout("indicator-on-1", []core.Pt{
		{X:-0.000000, Y:-128.000000},
		{X:-0.000000, Y:128.000000},
	}, []string{
		"PinA",
		"PinB",
	})
	part.RegisterVectorHitBounds("indicator-on-1", -63.158000, -128.000000, 63.158000, 128.000000)
	part.RegisterVectorDraw("indicator-on-2", drawVector_indicator_on_2)
	part.RegisterPinLayout("indicator-on-2", []core.Pt{
		{X:128.000000, Y:-0.000000},
		{X:-128.000000, Y:-0.000000},
	}, []string{
		"PinA",
		"PinB",
	})
	part.RegisterVectorHitBounds("indicator-on-2", -128.000000, -63.158000, 128.000000, 63.158000)
	part.RegisterVectorDraw("indicator-on-3", drawVector_indicator_on_3)
	part.RegisterPinLayout("indicator-on-3", []core.Pt{
		{X:0.000000, Y:128.000000},
		{X:0.000000, Y:-128.000000},
	}, []string{
		"PinA",
		"PinB",
	})
	part.RegisterVectorHitBounds("indicator-on-3", -63.158000, -128.000000, 63.158000, 128.000000)
}

func drawVector_indicator_off_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000000, 0.000000, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-62.940000, 0.000000, -134.098000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{62.940000, 0.000000, 134.098000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.536277, -45.001704, -45.351015, 45.527791}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.254848, -45.254848, 45.274647, 45.632443}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000000, 0.000000, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-0.000000, -62.940000, -0.000000, -134.098000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-0.000000, 62.940000, -0.000000, 134.098000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.001704, 45.536277, -45.527791, -45.351015}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.254848, -45.254848, -45.632443, 45.274647}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000000, -0.000000, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{62.940000, -0.000000, 134.098000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-62.940000, -0.000000, -134.098000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.536277, 45.001704, 45.351015, -45.527791}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.254848, 45.254848, -45.274647, -45.632443}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_off_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000000, -0.000000, 63.158000, color.RGBA{R:255, G:255, B:255, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{0.000000, 62.940000, 0.000000, 134.098000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{0.000000, -62.940000, 0.000000, -134.098000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.001704, -45.536277, 45.527791, 45.351015}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.254848, 45.254848, 45.632443, -45.274647}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000000, 0.000000, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, 0.000000, -128.000000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{64.000000, 0.000000, 128.000000, 0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.695000, -45.144000, -45.192000, 45.385000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.391000, -45.303000, 45.138000, 45.584000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000000, 0.000000, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{-0.000000, -64.000000, -0.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-0.000000, 64.000000, -0.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.144000, 45.695000, -45.385000, -45.192000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.303000, -45.391000, -45.584000, 45.138000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, -0.000000, -0.000000, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{64.000000, -0.000000, 128.000000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-64.000000, -0.000000, -128.000000, -0.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.695000, 45.144000, 45.192000, -45.385000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{45.391000, 45.303000, -45.138000, -45.584000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_indicator_on_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGCircle(ctx, base, 0.000000, -0.000000, 63.158000, color.RGBA{R:255, G:172, B:0, A:255}, true, color.RGBA{R:0, G:0, B:0, A:255}, 10.000000, true)
	part.DrawVGPolyline(ctx, base, []float64{0.000000, 64.000000, 0.000000, 128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{0.000000, -64.000000, 0.000000, -128.000000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.144000, -45.695000, 45.385000, 45.192000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGPolyline(ctx, base, []float64{-45.303000, 45.391000, 45.584000, -45.138000}, false, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

