// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Pin fields match red authoring circle id attributes in catalog SVGs (see vectors_gen.go RegisterPinLayout).

package vcc

import "coilforge/internal/core"

// VccPinIDs holds stable pin identity for this catalog type.
type VccPinIDs struct {
	VCC core.PinID `json:"vCC"`
}

// vccPinMarkerMap maps SVG marker ids from the vector layout to pin IDs for anchor placement.
func vccPinMarkerMap(self *Vcc) map[string]core.PinID {
	return map[string]core.PinID{
		"VCC": self.VCC,
	}
}

// assignNewVccPins allocates fresh pin IDs (e.g. clone).
func assignNewVccPins(self *Vcc, alloc func() core.PinID) {
	self.VCC = alloc()
}
