// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Pin fields match red authoring circle id attributes in catalog SVGs (see vectors_gen.go RegisterPinLayout).

package switches

import "coilforge/internal/core"

// SwitchesPinIDs holds stable pin identity for this catalog type.
type SwitchesPinIDs struct {
	A core.PinID `json:"a"`
	B core.PinID `json:"b"`
}

// switchesPinMarkerMap maps SVG marker ids from the vector layout to pin IDs for anchor placement.
func switchesPinMarkerMap(self *Switches) map[string]core.PinID {
	return map[string]core.PinID{
		"A": self.A,
		"B": self.B,
	}
}

// assignNewSwitchesPins allocates fresh pin IDs (e.g. clone).
func assignNewSwitchesPins(self *Switches, alloc func() core.PinID) {
	self.A = alloc()
	self.B = alloc()
}
