// Code generated by scripts/gen_part_vectors.go; DO NOT EDIT.
// Vector names are <stem>-<0..n> from schematic SVGs (underscores → hyphens), excluding toolbar btn_*.svg.
// Without _45: indices 0..3 are quarter-turn steps of the canonical SVG.
// With *-stem_45.svg: indices 0..7 interleave canonical and diagonal art (even idx = canonical, odd = _45); idx/2 is the quarter-turn on that source.
// Each suffix bakes k BasePart.Rotation steps in SVG user space (same convention as core.LocalToWorld); catalog draw passes identity rotation.
package switches

import (
	"coilforge/internal/core"
	"coilforge/internal/part"
	"image/color"
)

const RotationSlots = 4

func init() {
	part.RegisterVectorDraw("switch-off-0", drawVector_switch_off_0)
	part.RegisterPinLayout("switch-off-0", []core.Pt{
		{X:-128.000000, Y:-0.000000},
		{X:128.000000, Y:-0.000000},
	}, []string{
		"A",
		"B",
	})
	part.RegisterVectorHitBounds("switch-off-0", -128.000000, -64.000000, 128.000000, 4.000000)
	part.RegisterVectorDraw("switch-off-1", drawVector_switch_off_1)
	part.RegisterPinLayout("switch-off-1", []core.Pt{
		{X:0.000000, Y:-128.000000},
		{X:0.000000, Y:128.000000},
	}, []string{
		"A",
		"B",
	})
	part.RegisterVectorHitBounds("switch-off-1", -4.000000, -128.000000, 64.000000, 128.000000)
	part.RegisterVectorDraw("switch-off-2", drawVector_switch_off_2)
	part.RegisterPinLayout("switch-off-2", []core.Pt{
		{X:128.000000, Y:0.000000},
		{X:-128.000000, Y:0.000000},
	}, []string{
		"A",
		"B",
	})
	part.RegisterVectorHitBounds("switch-off-2", -128.000000, -4.000000, 128.000000, 64.000000)
	part.RegisterVectorDraw("switch-off-3", drawVector_switch_off_3)
	part.RegisterPinLayout("switch-off-3", []core.Pt{
		{X:-0.000000, Y:128.000000},
		{X:-0.000000, Y:-128.000000},
	}, []string{
		"A",
		"B",
	})
	part.RegisterVectorHitBounds("switch-off-3", -64.000000, -128.000000, 4.000000, 128.000000)
	part.RegisterVectorDraw("switch-on-0", drawVector_switch_on_0)
	part.RegisterPinLayout("switch-on-0", []core.Pt{
		{X:-128.000000, Y:-0.000000},
		{X:128.000000, Y:-0.000000},
	}, []string{
		"A",
		"B",
	})
	part.RegisterVectorHitBounds("switch-on-0", -128.000000, -39.000000, 128.000000, 4.000000)
	part.RegisterVectorDraw("switch-on-1", drawVector_switch_on_1)
	part.RegisterPinLayout("switch-on-1", []core.Pt{
		{X:0.000000, Y:-128.000000},
		{X:0.000000, Y:128.000000},
	}, []string{
		"A",
		"B",
	})
	part.RegisterVectorHitBounds("switch-on-1", -4.000000, -128.000000, 39.000000, 128.000000)
	part.RegisterVectorDraw("switch-on-2", drawVector_switch_on_2)
	part.RegisterPinLayout("switch-on-2", []core.Pt{
		{X:128.000000, Y:0.000000},
		{X:-128.000000, Y:0.000000},
	}, []string{
		"A",
		"B",
	})
	part.RegisterVectorHitBounds("switch-on-2", -128.000000, -4.000000, 128.000000, 39.000000)
	part.RegisterVectorDraw("switch-on-3", drawVector_switch_on_3)
	part.RegisterPinLayout("switch-on-3", []core.Pt{
		{X:-0.000000, Y:128.000000},
		{X:-0.000000, Y:-128.000000},
	}, []string{
		"A",
		"B",
	})
	part.RegisterVectorHitBounds("switch-on-3", -39.000000, -128.000000, 4.000000, 128.000000)
}

func drawVector_switch_off_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -128.000000, -0.000000, -64.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 52.000000, -0.000000, 128.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 57.000000, 4.000000, 57.000000, -22.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 57.000000, 4.000000, 57.000000, -22.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 42.000000, -13.000000, 60.000000, -31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 72.000000, -13.000000, 54.000000, -31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -66.000000, 0.000000, 73.000000, -64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_switch_off_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 0.000000, -128.000000, 0.000000, -64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 52.000000, 0.000000, 128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -4.000000, 57.000000, 22.000000, 57.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -4.000000, 57.000000, 22.000000, 57.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 13.000000, 42.000000, 31.000000, 60.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 13.000000, 72.000000, 31.000000, 54.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -66.000000, 64.000000, 73.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_switch_off_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 128.000000, 0.000000, 64.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -52.000000, 0.000000, -128.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -57.000000, -4.000000, -57.000000, 22.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -57.000000, -4.000000, -57.000000, 22.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -42.000000, 13.000000, -60.000000, 31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -72.000000, 13.000000, -54.000000, 31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 66.000000, -0.000000, -73.000000, 64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_switch_off_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -0.000000, 128.000000, -0.000000, 64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -52.000000, -0.000000, -128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 4.000000, -57.000000, -22.000000, -57.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 4.000000, -57.000000, -22.000000, -57.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -13.000000, -42.000000, -31.000000, -60.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -13.000000, -72.000000, -31.000000, -54.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 66.000000, -64.000000, -73.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_switch_on_0(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -128.000000, -0.000000, -64.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 52.000000, -0.000000, 128.000000, -0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 57.000000, 4.000000, 57.000000, -22.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 57.000000, 4.000000, 57.000000, -22.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 42.000000, -13.000000, 60.000000, -31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 72.000000, -13.000000, 54.000000, -31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -66.000000, 0.000000, 72.000000, -39.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_switch_on_1(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 0.000000, -128.000000, 0.000000, -64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 52.000000, 0.000000, 128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -4.000000, 57.000000, 22.000000, 57.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -4.000000, 57.000000, 22.000000, 57.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 13.000000, 42.000000, 31.000000, 60.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 13.000000, 72.000000, 31.000000, 54.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -66.000000, 39.000000, 72.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_switch_on_2(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, 128.000000, 0.000000, 64.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -52.000000, 0.000000, -128.000000, 0.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -57.000000, -4.000000, -57.000000, 22.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -57.000000, -4.000000, -57.000000, 22.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -42.000000, 13.000000, -60.000000, 31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -72.000000, 13.000000, -54.000000, 31.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 66.000000, -0.000000, -72.000000, 39.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

func drawVector_switch_on_3(ctx part.DrawContext, base core.BasePart) bool {
	part.DrawVGLine(ctx, base, -0.000000, 128.000000, -0.000000, 64.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -0.000000, -52.000000, -0.000000, -128.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 4.000000, -57.000000, -22.000000, -57.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 4.000000, -57.000000, -22.000000, -57.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -13.000000, -42.000000, -31.000000, -60.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, -13.000000, -72.000000, -31.000000, -54.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	part.DrawVGLine(ctx, base, 0.000000, 66.000000, -39.000000, -72.000000, 10.000000, color.RGBA{R:0, G:0, B:0, A:255})
	return true
}

